### ISSUE TITLE
Connection error making token request to 'https://oauth2.googleapis.com/token': The request timed out..

### ISSUE THREAD

**Issue by tanand7** [google/GoogleSignIn-iOS#100]
**Google sign in NOT working and returns connection error.**

```
Error! Optional(Error Domain=org.openid.appauth.general Code=-5 "Connection error making token request to 'https://oauth2.googleapis.com/token': The request timed out.." UserInfo={NSLocalizedDescription=Connection error making token request to 'https://oauth2.googleapis.com/token': The request timed out.., NSUnderlyingError=0x600000634030 {Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x6000006392c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0F0E1E47-8CBA-499F-AEE1-957F160BB706>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0F0E1E47-8CBA-499F-AEE1-957F160BB706>.<2>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://oauth2.googleapis.com/token, NSErrorFailingURLKey=https://oauth2.googleapis.com/token, _kCFStreamErrorDomainKey=4}}})
```

**To reproduce:**
 follow the instructions from https://developers.google.com/identity/sign-in/ios/start

[Clone the project](git clone https://github.com/google/GoogleSignIn-iOS) and run it to the device/simulator and click the sign in button.

**Environment:**

Xcode 13.2.1 (13C100)

Device: Simulator/Phone iOS 15.2

**Comment by tanand7** [comment]
Seems to be resolved automatically

**Comment by KeyurPrajapati** [comment]
I am facing the same error from yesterday.

**Comment by petea** [comment]
Are you still able to reproduce the time out error?

**Comment by KeyurPrajapati** [comment]
Yes, 
<3C3C466E-FF37-4146-851C-7FAD9EFD0C17>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x60000218d530 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3C3C466E-FF37-4146-851C-7FAD9EFD0C17>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3C3C466E-FF37-4146-851C-7FAD9EFD0C17>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://oauth2.googleapis.com/token, NSErrorFailingURLKey=https://oauth2.googleapis.com/token, _kCFStreamErrorDomainKey=4}

**Comment by rjt3662** [comment]
I'm also facing this error
```
finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." 
UserInfo={_kCFStreamErrorCodeKey=60, NSUnderlyingError=0x600003a739f0 
{Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" 
UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en1, _kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <7E276A0C-D984-426B-BE35-1D9D851D4AED>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <7E276A0C-D984-426B-BE35-1D9D851D4AED>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://oauth2.googleapis.com/token, NSErrorFailingURLKey=https://oauth2.googleapis.com/token, _kCFStreamErrorDomainKey=1}
Connection error making token request to 'https://oauth2.googleapis.com/token': The request timed out..
```
Does anyone got its solution?

**Comment by harrymash2006** [comment]
I am also having this issue

**Comment by tanand7** [comment]
This is happening randomly. Sometimes it works and sometimes it doesn't.

**Comment by rahulpatel2311** [comment]
@petea 
I am also facing the same issue for 8 days.
Any update?

**Comment by AravindBG** [comment]
We are also facing the same issue for the past couple of days. It won't work for some ISPs. But work on others.

**Comment by j-dogcoder** [comment]
I am facing this on both the Apple Mail client, and the Spark mail client.

**Comment by ecunha-ta** [comment]
Good afternoon, 
any news on this? 
Regards

**Comment by fbrunelli84** [comment]
I'm also interested in this issue

**Comment by arioch1984** [comment]
I'm also interested in this issue

**Comment by sharikovvladislav** [comment]
I am having the same. I can't use the GoogleSignIn for the same reasons. I am trying to signIn from an app written in flutter. I am using the following package: https://pub.dev/packages/google_sign_in 

The error is: 
```
value	__NSCFString *	@"Connection error making token request to 'https://oauth2.googleapis.com/token': The request timed out.."	0x00006000039ec380
```

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/f1cb7c7e-61e6-49c1-bbda-a5855145a3f4">

**Comment by sharikovvladislav** [comment]
I am having the same. I can't use the GoogleSignIn for the same reasons. I am trying to signIn from an app written in flutter. I am using the following package: https://pub.dev/packages/google_sign_in 

The error is: 
```
value	__NSCFString *	@"Connection error making token request to 'https://oauth2.googleapis.com/token': The request timed out.."	0x00006000039ec380
```

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/f1cb7c7e-61e6-49c1-bbda-a5855145a3f4">

@petea do you have any ideas on why it is happening? It looks like a temporary issue 🤔 Very painful, though.

In addition to that, I don't have any error or anything on Flutter side
