### ISSUE TITLE
Cannot access fetcherAuthorizer property on GIDAuthentication from swift

### ISSUE THREAD

**Issue by lilpit** [google/GoogleSignIn-iOS#106]
The `fetcherAuthorizer` method signature is not visible in swift generated interface of `GIDAuthentication` . 
This prevent the use of this library to work with https://github.com/google/google-api-objectivec-client-for-rest from swift
<img width="1649" alt="Screenshot 2022-03-10 at 15 08 22" src="https://user-images.githubusercontent.com/654251/157678915-04e0112e-4837-46a8-b444-a7a45427818d.png">

**Comment by petea** [comment]
@lilpit thanks for spotting this, we'll have a fix in the next release.
