### ISSUE TITLE
GTMAppAuth minimum platform Error

### ISSUE THREAD

**Issue by gusadi09** [google/GoogleSignIn-iOS#108]
`Showing Recent Messages
The package product 'GTMAppAuth' requires minimum platform version 10.11 for the macOS platform, but this target supports 10.10`

I get this error in macOS App, but in package.swift I get set the platform with `.macOS(.v11)` I think that enough. but this error is still showing

**Comment by Moriquendi** [comment]
Same here

**Comment by petea** [comment]
Despite the assumption that SPM is making here, GSI 6.1 does not support macOS development.  Work is underway to provide support with the upcoming 6.2 release.

**Comment by gusadi09** [comment]
really? I'm so excited waiting for the 6.2 release. I think it will make development with SwiftUI easier

**Comment by karthikAdaptavant** [comment]
+1

**Comment by SmartJSONEditor** [comment]
I am using 6.2.1 but sign in do not work on macOS, neighter running the example app DaysUntilBirthday.xcodeproj the macOS do not show any sign in window

**Comment by petea** [comment]
Closing the original issue here as GSI 6.2 now provides explicit support for macOS 10.15+.

@SmartJSONEditor could you provide details about the macOS environment in which you're seeing problems with the sign-in flow?  The macOS version and default browser would be relevant.  Feel free to [create a new issue](https://github.com/google/GoogleSignIn-iOS/issues/new).
