### ISSUE TITLE
ITMS-90049: GoogleUtilities_Environment replaced with GoogleUtilities\u005fEnvironment

### ISSUE THREAD

**Issue by kzyryanov** [google/GoogleSignIn-iOS#124]
Xcode v13.3.1
GoogleSignIn-iOS v6.1.0

During upload of our app we started to get the following error.

> ERROR ITMS-90049: "This bundle is invalid. The bundle at path Payload/App.app/Frameworks/GoogleUtilities_Environment.framework has an invalid CFBundleIdentifier 'GoogleUtilities_Environment' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'GoogleUtilities\u005fEnvironment' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105]"

I don't see any changes on our side which could've led to this problem.
Could you please take a look?

**Comment by petea** [comment]
Google Sign-In makes use of [GoogleUtilities](https://github.com/google/GoogleUtilities) for its test targets, but not for the library itself.  Are you depending on GoogleUtilities directly or via some other library such that it would explain its bundle being present in your uploaded app?

**Comment by kzyryanov** [comment]
@petea Thanks for reply

We don't use GoogleUtilities directly only through GoogleSignIn. And we are trying to upload using latest for today Xcode 13.3.1

**Comment by kzyryanov** [comment]
Some logs from xcode when we do archive
We tried to update packages to the latest version and it uses GoogleUtilities 7.7.1 now
Looks like the problem with `GoogleUtilities_Logger` and `GoogleUtilities_Environment`

Package.resolved
>     {
>       "identity" : "googleutilities",
>       "kind" : "remoteSourceControl",
>       "location" : "https://github.com/google/GoogleUtilities.git",
>       "state" : {
>         "revision" : "f4abe56ce62a779e64b525eb133c8fc2a84bbc1f",
>         "version" : "7.7.1"
>       }
>     }

> ProcessInfoPlistFile /OurApp/Build/Intermediates.noindex/ArchiveIntermediates/OurApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Environment.framework/Info.plist /OurApp/Build/Intermediates.noindex/ArchiveIntermediates/OurApp/IntermediateBuildFilesPath/GoogleUtilities.build/Release-iphoneos/GoogleUtilities_Environment.build/empty-GoogleUtilities_Environment.plist (in target 'GoogleUtilities_Environment' from project 'GoogleUtilities')
>     cd /OurApp/SourcePackages/checkouts/GoogleUtilities
>     builtin-infoPlistUtility /OurApp/Build/Intermediates.noindex/ArchiveIntermediates/OurApp/IntermediateBuildFilesPath/GoogleUtilities.build/Release-iphoneos/GoogleUtilities_Environment.build/empty-GoogleUtilities_Environment.plist -producttype com.apple.product-type.framework -expandbuildsettings -format binary -platform iphoneos -o /OurApp/Build/Intermediates.noindex/ArchiveIntermediates/OurApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Environment.framework/Info.plist
> 
> warning: invalid character in Bundle Identifier. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters. (in target 'GoogleUtilities_Environment' from project 'GoogleUtilities')


> ProcessInfoPlistFile /.../DerivedData/OurApp/Build/Intermediates.noindex/ArchiveIntermediates/OurApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Logger.framework/Info.plist /Users/jenkins/Library/Developer/Xcode/DerivedData/OurApp/Build/Intermediates.noindex/ArchiveIntermediates/OurApp/IntermediateBuildFilesPath/GoogleUtilities.build/Release-iphoneos/GoogleUtilities_Logger.build/empty-GoogleUtilities_Logger.plist (in target 'GoogleUtilities_Logger' from project 'GoogleUtilities')
>     cd /OurApp/SourcePackages/checkouts/GoogleUtilities
>     builtin-infoPlistUtility /Users/jenkins/Library/Developer/Xcode/DerivedData/OurApp/Build/Intermediates.noindex/ArchiveIntermediates/OurApp/IntermediateBuildFilesPath/GoogleUtilities.build/Release-iphoneos/GoogleUtilities_Logger.build/empty-GoogleUtilities_Logger.plist -producttype com.apple.product-type.framework -expandbuildsettings -format binary -platform iphoneos -o /OurApp/Build/Intermediates.noindex/ArchiveIntermediates/OurApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Logger.framework/Info.plist
> 
> warning: invalid character in Bundle Identifier. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters. (in target 'GoogleUtilities_Logger' from project 'GoogleUtilities')

**Comment by kzyryanov** [comment]
We found that the problem not with GoogleSignIn but with firebase-ios-sdk
When we add firebase-ios-sdk as a dependency for framework target it makes that error (with app target all good)
