### ISSUE TITLE
How to pass in nonce?

### ISSUE THREAD

**Issue by DanMossa** [google/GoogleSignIn-iOS#135]
Context:
You can not pass a rawNonce to signInWithGoogle.

When using signInWithGoogle on Android, the returned idToken does not return a nonce. This makes sense because a rawNonce is not passed in.

The same exact code when run on iOS, returns a hashed nonce in the idToken. This does not make sense since we can not pass in a nonce. Where is the nonce coming from?

**Comment by petea** [comment]
> How can I get the originally generated value?

The nonce generated by AppAuth isn't available via the Google Sign-In API surface.  Currently, the recommended approach to [server-side validation of the ID token](https://developers.google.com/identity/sign-in/ios/backend-auth) doesn't include validation of the nonce.

> Is there no way to explicitly set this value?

AppAuth allows you to provide a specific nonce, if desired.  However, Google Sign-In does not expose this capability in its API surface.

**Comment by toshi0383** [comment]
We need nonce support, too.
Apple and LINE supports this, so please consider.

**Comment by petea** [comment]
@DanMossa, PRs are always welcome.  Can you provide more detail on the specific use cases that are blocked here?  Are they all related to server-side verification of the nonce?

@toshi0383 is the existing automatic client-side nonce generation / validation not adequate for your needs?

**Comment by toshi0383** [comment]
> automatic client-side nonce generation

@petea We generate nonce in our server-side, so we need manual way to do this.
I have a brand new branch for this, so will tackle in a PR in a few minutes!

**Comment by toshi0383** [comment]
Done!
https://github.com/google/GoogleSignIn-iOS/pull/244

**Comment by mdmathias** [comment]
Hi all! Many apologies for the delay. Thanks for your patience.

Would you be able to share more information about your use-case? It seems to deviate from the typical use case where the `nonce` is generated by the client.

In general, it seems fine for GSI to provide an API to ingest a `nonce` to pass along to [OIDAuthorizationRequest](https://github.com/openid/AppAuth-iOS/blob/master/Source/AppAuthCore/OIDAuthorizationRequest.h#L211) in AppAuth.

**Comment by hf** [comment]
> The nonce generated by AppAuth isn't available via the Google Sign-In API surface. Currently, the recommended approach to [server-side validation of the ID token](https://developers.google.com/identity/sign-in/ios/backend-auth) doesn't include validation of the nonce.

This is not true. The OIDC spec which Google follows [explicitly states](https://openid.net/specs/openid-connect-core-1_0.html#:~:text=If%20present%20in%20the%20ID%20Token%2C%20Clients%20MUST%20verify%20that%20the%20nonce%20Claim%20Value%20is%20equal%20to%20the%20value%20of%20the%20nonce%20parameter%20sent%20in%20the%20Authentication%20Request.):

> nonce
> String value used to associate a Client session with an ID Token, and to mitigate replay attacks. The value is passed through unmodified from the Authentication Request to the ID Token. If present in the ID Token, Clients MUST verify that the nonce Claim Value is equal to the value of the nonce parameter sent in the Authentication Request. If present in the Authentication Request, Authorization Servers MUST include a nonce Claim in the ID Token with the Claim Value being the nonce value sent in the Authentication Request. Authorization Servers SHOULD perform no other processing on nonce values used. The nonce value is a case sensitive string.

Please allow for people to be able to extract the nonce you send to Google.

**Comment by SunilKividor** [comment]
@petea @toshi0383 can u help me setting up nonce in the google sign in package? Its an  urgent usecase

**Comment by toshi0383** [comment]
@SunilKividor Hire someone and leave.
I have nothing to do with ur use case.
Stop mentioning us for nothing.

**Comment by SunilKividor** [comment]
Thankyou for the response. We have moved to google credential management for setting up authentication with nonce. I appreciate your time.

**Comment by Massimiliano-solutiontech** [comment]
Any news on that? The only way to set the `nonce` is to use [AppAuth](https://github.com/openid/AppAuth-iOS/)?

**Comment by toshi0383** [comment]
FYI my fork is an option too. https://github.com/google/GoogleSignIn-iOS/pull/244
We're using this in production without any issues.

**Comment by vonovak** [comment]
I have opened a PR to support this: https://github.com/google/GoogleSignIn-iOS/pull/402

**Comment by GNUGradyn** [comment]
been a few months, any movement on this PR?

**Comment by riderx** [comment]
Been done here: https://github.com/google/GoogleSignIn-iOS/pull/402

**Comment by brnnmrls** [comment]
Additional note: If you're using [Google Sign-In 8.1.0-vwg-eap-1.0.x](https://github.com/google/GoogleSignIn-iOS/releases/tag/8.1.0-vwg-eap-1.0.0) to fix this issue, you should know that we are getting rid of these pre-releases soon. Please use official release Google Sign-In 9.0.0 instead.
