### ISSUE TITLE
Unable to load Google icon image url

### ISSUE THREAD

**Issue by Vong3432** [google/GoogleSignIn-iOS#194]
When I tried to run the app, it throws this error message ``GoogleSignInSwift/GoogleSignInButton.swift:134: Fatal error: Unable to load Google icon image url: unableToLoadGoogleIcon(name: "google")``. 

Actually, I have already wrapped the ``GIDSignInButton()`` with ``UIViewRepresentable`` because I thought there was no "SwiftUI" way to implement the Google Sign-In button until I saw this [documentation](https://developers.google.com/identity/sign-in/ios/start-integrating), but I'm not sure if this error occurs because I'm missing something, or if it's a url issue.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/36991424/183301920-704ce31a-cb5c-4b24-8059-1554b805dbf2.png">

### Environment:
- Language: SwiftUI
- Deployment info: iOS 15.0
- Xcode: 13.4.1

### SwiftUI:
```
GoogleSignInButton {
    //                 
}
```

### Podfile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Finebuck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Finebuck
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '9.3.0'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  
  target 'FinebuckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinebuckUITests' do
    # Pods for testing
  end

end
```

**Comment by mdmathias** [comment]
I'm not able to reproduce this issue. I set up a little project using CocoaPods to depend upon GoogleSignIn and GoogleSignInSwift. Take a look at the screenshot below. Perhaps this is an issue with your CocoaPods setup? 

![image](https://user-images.githubusercontent.com/4029922/184048933-e455d782-ed96-4bc6-afda-523c2154631b.png)

**Comment by Vong3432** [comment]
I did some changes and this error disappears after I commented out `use_frameworks!` in the Podfile, but the error would still exist if we don't comment out `use_frameworks!`.

**Comment by mdmathias** [comment]
Could you tell us a little more about your use of `use_frameworks!`? Is there a reason for it? My understanding is that it was common to add `use_frameworks!` to a `Podfile` in the earlier days of Swift when it did not support static libraries (and the project with Swift pods therefore needed to use dynamic frameworks). 

I'll look at this issue some more today and will follow up here when I have an update.

**Comment by Vong3432** [comment]
So far not really, my current project does not have any dependencies that requires me to add `use_frameworks!`. 

Thank you for pointing the use of `use_frameworks!`, I always thought it was common to put that in the Podfile before as it was added automatically every time I created the Podfile. I should have read more carefully about the use of `use_frameworks` though, my bad.

**Comment by mdmathias** [comment]
You can read more about `use_frameworks!` in CocoaPods's releases:

1. `use_frameworks!` is added: https://blog.cocoapods.org/CocoaPods-0.36/
2. Swift static libraries are supported and `use_frameworks!` no longer required: https://blog.cocoapods.org/CocoaPods-1.5.0/

**Comment by mdmathias** [comment]
Seems like [this is a CocoaPods bug](https://github.com/CocoaPods/CocoaPods/issues/4897)?
