### ISSUE TITLE
Compile project for Apple silicon M1 macs

### ISSUE THREAD

**Issue by mmdumi** [google/GoogleSignIn-iOS#22]
Hi,
Apple silicon M1 macs are used more and more by developers and we are currently unable to compile projects that depend on the GoogleSignIn functionality.
I haven't found a public tracker where to post this request for Google Signin so this is why I'm writing here hoping that I can find somebody who can help.
Can you please recompile the project https://developers.google.com/identity/sign-in/ios/start?ver=swift as an .xcframework release ?
Thank you

**Comment by petea** [comment]
With the [6.0.0 release](https://github.com/google/GoogleSignIn-iOS/releases/tag/6.0.0), Google Sign-In has moved to source distribution and can now be used with the Simulator on M1 Macs.
