### ISSUE TITLE
`addScopes` callback not called when nested

### ISSUE THREAD

**Issue by ivopintodasilva** [google/GoogleSignIn-iOS#24]
Hi, I'm working on updating `GoogleSignIn` to the latest version and facing a problem regarding the `addScopes` function.

Since we are now not able to Sign In with the necessary scopes, I am trying to add them as soon as the user is signed in.
It turns out that by chaining both methods, the callback I send to `addScopes` is never executed.

```
GIDSignIn.sharedInstance.signIn(with: configuration, presenting: presentingViewController) { user, error in
    
    guard error == nil else {
        completion(user, error)
        return
    }
                    
    GIDSignIn.sharedInstance.addScopes(
        scopes,
        presenting: presentingViewController,
        callback: {
            // This callback is never executed
            print(">>> addScopes callback")
            completion($0, $1)
        }
    )
}
```

Testing it manually I'm able to see:

1. The web view being presented for the regular sign in and being dismissed when it succeeds
2. The web view for allowing permissions to be added and dismissed when tapping "Allow"

After these two steps, nothing happens 😔 Am I missing something?

In my opinion the optimal solution would be being able to supply the scopes directly to the `signIn` method so that both tasks could be done in one step instead of two (like suggested on #23) but I wanted to flag this finding I'm running into as well.

Thanks for the great work!

**Comment by ivopintodasilva** [comment]
The above behavior can be observed in this sample project: https://github.com/ivopintodasilva/GoogleSignIn-AddScopeTest

`GoogleSignIn` is added to the project as a Swift Package and there are instructions in the `README.md` file on how to run the project.

**Comment by ismetanin** [comment]
Hi! I faced the same issue when migrating to 6.0.0

Agree with @ivopintodasilva that setting scopes in `signIn` would be way more convenient. For me, it looks strange when we need to show sign-in flow and then right after that ask for scopes in the case when we immediately need to do something with these scopes

**Comment by kundanjadhav** [comment]
Hi, I am facing similar issue. Due to this I am not able to update to latest version. Let me know when you get any update regarding this.

**Comment by LightWish** [comment]
Hi! I was facing the same issue.
I've found workaround.  I see that an issue is in
 ```swift
- (void)addCompletionCallback:(GIDAuthFlow *)authFlow 
```
 function.
 `self->_currentOptions.callback(self->_currentUser, handlerAuthFlow.error);` 
is waiting while my second block with `addScopes` is working, so it calls `self->_currentOptions = nil`, after saving new completion block. 

My working solution is to call `addScopes` in `DispatchQueue.main.async `

```swift
DispatchQueue.main.async { [weak self] in
                guard let self = self else { return }
                self.engine.addScopes(scopes, presenting: controller, callback: callback)
}
```

**Comment by jkichline** [comment]
Why are Google products always in beta and we are the guinea pigs? This addScopes method is idiotic. We used to be able to set the scope and sign in. Why is the user now having to be presented with another interface for approval? Why completely change your SDK and not provide deprecation notes to aid in the transition? This seems poorly executed. We need the ability to set the scopes required prior to sign-in as before and which is possible in the "internal options".

**Comment by petea** [comment]
@jkichline please refer to #23 for an explanation of the `addScopes` API surface change you're referring to and feel free to leave any relevant feedback there.  The implications of the change you mention are called out in the [changelog](https://github.com/google/GoogleSignIn-iOS/blob/main/CHANGELOG.md) but not elaborated on in the [migration guide](https://developers.google.com/identity/sign-in/ios/quick-migration-guide), which I'll address.  You can refer to the [Client-side Access](https://developers.google.com/identity/sign-in/ios/api-access) guide for a detailed discussion.
