### ISSUE TITLE
Can we sign in with Google IAP without using this library?

### ISSUE THREAD

**Issue by gsabran** [google/GoogleSignIn-iOS#255]
I'm trying to add support for Google IAP auth in my app, which already uses [AppAuth](https://github.com/openid/AppAuth-iOS). I'm able to get an Auth Code, and need to then get an ID Token. [The documentation from Google](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_a_mobile_app) however says that I should use this library to do the entire auth.

I would much prefer not adding this library to my app to limit the app size increase.

Is it possible to to get an ID Token from an Auth code and my iOS app ID with just making some request, similarly to [how Web apps can do](https://cloud.google.com/iap/docs/authentication-howto#signing_in_to_the_application) with their app secret? If so what would it be?

Thanks a lot for the help.

**Comment by petea** [comment]
Yes, you can use AppAuth directly here if you'd prefer.  Please see the [AppAuth Examples](https://github.com/openid/AppAuth-iOS/tree/master/Examples) for guidance on how to execute your auth flow.  AppAuth can perform the auth code exchange for you in the same step as your authorization flow or as a separate step following a successful authorization.  A secret will not be needed for a [Google native iOS client](https://github.com/openid/AppAuth-iOS/blob/master/Examples/README-Google.md#ios).

Note that you'll need to set the `audience` parameter in your authorization request in order to get the same behavior as Google Sign-In's `serverClientID` property.

**Comment by gsabran** [comment]
Ok thanks a lot

**Comment by annieso** [comment]
hi @petea could you direct me to any documentation that explains how to set the `audience` parameter? I don't see it in the examples.

**Comment by petea** [comment]
> hi @petea could you direct me to any documentation that explains how to set the `audience` parameter? I don't see it in the examples.

If you're using Google Sign-In, the `audience` parameter is set via the `serverClientID` property of `GIDConfiguration`.  If you're using AppAuth directly, you would set `audience` in `additionalParameters` when constructing your `OIDAuthorizationRequest`.  You can see how Google Sign-In does this [here](https://github.com/google/GoogleSignIn-iOS/blob/87eddac9e41687a0e79afb1a0370ab9013cb3038/GoogleSignIn/Sources/GIDSignIn.m#L557).

**Comment by gsabran** [comment]
That's where we were looking. We have been trying to set the `audience` parameter (in a few different ways) Like
```swift
let authRequest = OIDAuthorizationRequest(
  configuration: configuration,
  clientId: "\(iosClientID).apps.googleusercontent.com",
  clientSecret: nil,
  scope: OIDScopeUtilities.scopes(with: Constants.registrationScopes),
  redirectURL: URL(string: "com.googleusercontent.apps.\(iosClientID):/oauth2redirect/google")!,
  responseType: OIDResponseTypeCode,
  state: nil,
  nonce: nil,
  codeVerifier: nil,
  codeChallenge: nil,
  codeChallengeMethod: nil,
  additionalParameters: [
    "audience": "\(serverClientID).apps.googleusercontent.com",
  ])

self.authFlow = OIDAuthState.authState(byPresenting: authRequest, presenting: viewController, callback: { authState, error in
  // authState?.lastTokenResponse?.idToken is set here
}
```
and set the `idToken` in our headers (ie `"authorization: Bearer \(idToken)"`)

After this we still get a 401 saying
```
Invalid IAP credentials: JWT audience doesn't match this application
('aud' claim (<iosClientID>.apps.googleusercontent.com) doesn't match
expected value (<serverClientID>.apps.googleusercontent.com))
```

I've verified through a proxy that the audience parameter is set correctly in the Google sign in view which opens
```
https://accounts.google.com/o/oauth2/v2/auth?
  response_type=code
  &scope=profile%20email
  &redirect_uri=com.googleusercontent.apps.<iOSClientId>:/oauth2redirect/google
  &client_id=<iOSClientId>.apps.googleusercontent.com
  &audience=<serverClientId>.apps.googleusercontent.com
```

Again, thanks a lot for your quick responses. It's rare on github :)

**Comment by gsabran** [comment]
So I think my audience is getting lost [here](https://github.com/openid/AppAuth-iOS/blob/b46216ab5c7a71634034cad03fc2ffe1b75005bf/Source/AppAuthCore/OIDAuthState.m#L147) where we have
```objc
OIDTokenRequest *tokenExchangeRequest =
  [authorizationResponse tokenExchangeRequest];
```

If I change this to
```objc
OIDTokenRequest *tokenExchangeRequest =
  [authorizationResponse tokenExchangeRequestWithAdditionalParameters: authorizationRequest.additionalParameters];
```
this works, but [the comment](https://github.com/openid/AppAuth-iOS/blob/b46216ab5c7a71634034cad03fc2ffe1b75005bf/Source/AppAuthCore/OIDAuthState.m#L143-L145) above this line makes me wonder whether this is the right change.
