### ISSUE TITLE
Compilation errors include of non-modular headers and duplicate interface definition

### ISSUE THREAD

**Issue by mzentric** [google/GoogleSignIn-iOS#258]
use_frameworks!
use_modular_headers!

Installing AppAuth (1.6.0)
Installing GTMAppAuth (1.3.1)
Installing GTMSessionFetcher (2.3.0)
Installing GoogleSignIn (6.2.4)
Installing RNGoogleSignin (8.2.1)

Hi guys!
 I'm using Google Sign-in with cocoapods through react-native.  I have an objective c and swift project with a few views in react native. One view in react native is used for logging in a specific type of user and a swift view is used for logging in another type of user.  Everything compiles and works wonderfully with react-native-google-sign version 7.2.2 which uses GoogleSignIn 6.1.0.  When I upgrade to use react-native-google-sign version 8.2.1 which uses GoogleSignIn 6.2.4.  I receive numerous compilation errors that I haven’t been able to figure out the issue.  

Podile has 
use_frameworks!
use_modular_headers!

And installed these versions

Installing AppAuth (1.6.0)
Installing GTMAppAuth (1.3.1)
Installing GTMSessionFetcher (2.3.0)
Installing GoogleSignIn (6.2.4)
Installing RNGoogleSignin (8.2.1)

using Xcode 13.4.1 
These are the errors:

In File GTMSessionFetcherLogging.h

App/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcherLogging.h:16:9: Include of non-modular header inside framework module 'GTMSessionFetcher.GTMSessionFetcherLogging': 'App/../Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h'

App/Pods/GoogleSignIn/GoogleSignIn/Sources/Public/GoogleSignIn/GIDAuthentication.h:24:9: While building module 'GTMAppAuth' imported from'App//Build/Products/Debug-iphonesimulator/GoogleSignIn/GoogleSignIn.framework/Headers/GIDAuthentication.h:24:

App/Pods/GTMAppAuth/GTMAppAuth/Sources/Public/GTMAppAuth/GTMAppAuthFetcherAuthorization.h:22:11: While building module 'GTMSessionFetcher' imported from'App//Build/Products/Debug-iphonesimulator/GTMAppAuth/GTMAppAuth.framework/Headers/GTMAppAuthFetcherAuthorization.h:22:

App/Nearpod/<module-includes>:1:9: In file included from <module-includes>:1:

App/Pods/Target Support Files/GTMSessionFetcher/GTMSessionFetcher-umbrella.h:14:9: In file included from'App//Build/Products/Debug-iphonesimulator/GTMSessionFetcher/GTMSessionFetcher.framework/Headers/GTMSessionFetcher-umbrella.h:14:

App/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcherLogging.h:16:9: In file included from'App//Build/Products/Debug-iphonesimulator/GTMSessionFetcher/GTMSessionFetcher.framework/Headers/GTMSessionFetcherLogging.h:16:

In file GTMSessionFetcher.h

App/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h:420:1: Duplicate interface definition for class 'GTMSessionFetcherUserDefaultsFactory'

App/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h:420:12: Previous definition is here

App/Pods/GoogleSignIn/GoogleSignIn/Sources/Public/GoogleSignIn/GIDAuthentication.h:24:9: While building module 'GTMAppAuth' imported from App/Build/Products/Debug-iphonesimulator/GoogleSignIn/GoogleSignIn.framework/Headers/GIDAuthentication.h:24:

App/Pods/GTMAppAuth/GTMAppAuth/Sources/Public/GTMAppAuth/GTMAppAuthFetcherAuthorization.h:22:11: While building module 'GTMSessionFetcher' imported from App/Build/Products/Debug-iphonesimulator/GTMAppAuth/GTMAppAuth.framework/Headers/GTMAppAuthFetcherAuthorization.h:22:

App/<module-includes>:1:9: In file included from <module-includes>:1:

App/Pods/Target Support Files/GTMSessionFetcher/GTMSessionFetcher-umbrella.h:14:9: In file included from App/Build/Products/Debug-iphonesimulator/GTMSessionFetcher/GTMSessionFetcher.framework/Headers/GTMSessionFetcher-umbrella.h:14:

App/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcherLogging.h:16:9: In file included from App/Build/Products/Debug-iphonesimulator/GTMSessionFetcher/GTMSessionFetcher.framework/Headers/GTMSessionFetcherLogging.h:16:

App/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h:430:28: Redefinition of 'GTMSessionFetcherError'

App/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h:430:28: Previous definition is here

App/Pods/GoogleSignIn/GoogleSignIn/Sources/Public/GoogleSignIn/GIDAuthentication.h:24:9: While building module 'GTMAppAuth' imported from App/Build/Products/Debug-iphonesimulator/GoogleSignIn/GoogleSignIn.framework/Headers/GIDAuthentication.h:24:

App/Pods/GTMAppAuth/GTMAppAuth/Sources/Public/GTMAppAuth/GTMAppAuthFetcherAuthorization.h:22:11: While building module 'GTMSessionFetcher' imported from App/Build/Products/Debug-iphonesimulator/GTMAppAuth/GTMAppAuth.framework/Headers/GTMAppAuthFetcherAuthorization.h:22:

App/<module-includes>:1:9: In file included from <module-includes>:1:

App/Pods/Target Support Files/GTMSessionFetcher/GTMSessionFetcher-umbrella.h:14:9: In file included from App/Build/Products/Debug-iphonesimulator/GTMSessionFetcher/GTMSessionFetcher.framework/Headers/GTMSessionFetcher-umbrella.h:14:

App/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcherLogging.h:16:9: In file included from App/Build/Products/Debug-iphonesimulator/GTMSessionFetcher/GTMSessionFetcher.framework/Headers/GTMSessionFetcherLogging.h:16:

Any solutions?

Thanks in advance
M

**Comment by mzentric** [comment]
After a few days and reaching out to you, I finally found the culprit.  I changed a "@import GoogleSignIn;" to "#import  #import <GoogleSignin/GIDSignIn.h>" in an objective c file.  
Thanks so much

**Comment by petea** [comment]
Glad you were able to get it building.  Had you considered removing `use_modular_headers!` from your podfile?
