### ISSUE TITLE
Sign in with additional scopes are unselected

### ISSUE THREAD

**Issue by BradDoddsProjects** [google/GoogleSignIn-iOS#260]
**Describe the bug**
Why are additional scopes unselected and not auto selected when adding additional scopes?

**To Reproduce**
```
let additionalScopes = ["https://www.googleapis.com/auth/youtube.readonly", "https://www.googleapis.com/auth/yt-analytics.readonly"]

GIDSignIn.sharedInstance.signIn(with: config, presenting: self, hint: nil, additionalScopes: additionalScopes) { [unowned self] user, error in
```

**Expected behavior**
Expected behavior of scopes being auto selected upon presenting what the app can access.
See screen shot.

**Screenshots**
[https://i.stack.imgur.com/So0Vk.png](url)
![Simulator Screen Shot - Max 14 0 - 2022-11-24 at 15 54 25](https://user-images.githubusercontent.com/60942618/203878125-0dba2710-ac75-418a-a4d0-c7b635da1e2d.png)

**Environment**
- iOS

**Additional context**
Our app is verified under the google console and does NOT show unsafe.
Our client ID is also verified by google.

**Comment by petea** [comment]
This is the intended behavior.  We require the user to provide explicit consent for each scope being requested in addition to basic profile.

Note that you can check which scopes the user grants after a successful sign-in and, at an appropriate moment, re-request the additional scopes via `addScopes` if needed.

https://developers.google.com/identity/sign-in/ios/api-access
