### ISSUE TITLE
Firebase Auth no longer works with latest GoogleSignIn... 

### ISSUE THREAD

**Issue by raymondwelch33** [google/GoogleSignIn-iOS#275]
**Describe the bug**
Check link: https://firebase.google.com/docs/auth/ios/google-signin

These documentation does NOT work, nor does it even make sense with latest (v7.0.0) GoogleSignIn-iOS..

**Comment by petea** [comment]
@raymondwelch33 apologies for the confusion.  @paulb777 is working to get Firebase docs updated for Google Sign-In 7.0.0.

For your example above you'll want to use the `tokenString` property of `GIDToken` to get the string representation of the token object:

`signInResult?.user.idToken.tokenString`

**Comment by paulb777** [comment]
https://github.com/firebase/quickstart-ios/pull/1465 demonstrates updating the FirebaseAuth quickstart to the GoogleSignIn 7.x APIs.

cc: @morganchen
