### ISSUE TITLE
GoogleSignIn does not define a clang module, cannot @import GoogleSignIn when built as a library

### ISSUE THREAD

**Issue by jmagman** [google/GoogleSignIn-iOS#32]
`GoogleSignIn` does not generate a clang module when built as a library instead of a framework.  This forces users to use `use_frameworks!` in their Podfile, which isn't the default.

### Steps to Reproduce
1. Remove `use_frameworks!` from Sample Podfile to generate as a library
https://github.com/google/GoogleSignIn-iOS/blob/954652d2e3f87218e3fd81bc0cffe88b0b226cce/Sample/Podfile#L2
2. Open SignInSampleForPod.xcworkspace and build.

Compilation failure: 
```
GoogleSignIn-iOS/Sample/Source/SignInViewController.h:19:9: Module 'GoogleSignIn' not found
```

<img width="629" alt="Screen Shot 2021-07-20 at 11 06 43 AM" src="https://user-images.githubusercontent.com/682784/126373657-0339ab41-51e1-4c92-a079-b3fa59dd80be.png">

### To fix
Add  `'DEFINES_MODULE' => 'YES'` to `pod_target_xcconfig`
https://github.com/google/GoogleSignIn-iOS/blob/5193a5befc1304c67201cc80f7d2818a0f8aadf4/GoogleSignIn.podspec#L38-L41
becomes:
```ruby
 s.pod_target_xcconfig = { 
   'GCC_PREPROCESSOR_DEFINITIONS' => 'GID_SDK_VERSION=' + s.version.to_s, 
   'HEADER_SEARCH_PATHS' => '"${PODS_TARGET_SRCROOT}"',
   'DEFINES_MODULE' => 'YES'
 } 
```
See "Modular Headers" section of https://blog.cocoapods.org/CocoaPods-1.5.0/

**Comment by piercifani** [comment]
Can we please fix this ASAP? This is breaking integration for many apps for versions 6.0 and up, and that version is required in order to use GSignIn in M1 Macs.

This is unacceptable.

**Comment by paulb777** [comment]
A possible workaround is adding `use_frameworks! :linkage => :static` to the Podfile. See the discussion in #33 for more context.

**Comment by piercifani** [comment]
Changing how all other Pods are built and linked sounds like a worse option than just add that flag to the Podspec to define the module, because it'll add a lot of uncertainty to all other libraries

**Comment by piercifani** [comment]
Guys, is anyone going to do anything about this or do we have to figure this out on our own?
