### ISSUE TITLE
VisionOS support on cocoapods

### ISSUE THREAD

**Issue by abbana** [google/GoogleSignIn-iOS#320]
Thank you.

**Comment by mdmathias** [comment]
Hi @abbana thanks for the issue. Not to be a stickler, but would you kindly follow the [issue format](https://github.com/google/GoogleSignIn-iOS/blob/main/.github/ISSUE_TEMPLATE/feature_request.md) we have set up for these sorts of requests? It will help us to evaluate your request and prioritize it if that is the next step we decide on.

**Comment by abbana** [comment]
Sure,

here it goes


---
name: Feature Request
about: Support for Apple VisionOS
title: "Support for Apple VisionOS"
labels: enhancement, triage
assignees: ""
---

**Is your feature request related to a problem you're having? Please describe.**
Please support new Apple VisionOS. This is needed for project porting or new projects on VisionOS

**Describe the solution you'd like**
Have that tested and supported

**Describe alternatives you've considered**
No alternatives available

**Additional context**
new OS from Apple

**Comment by abbana** [comment]
Hi,

hope you well.

Do you have an update on this please?

'UIScreen' is not available on visionOS and this does not compile.

**Comment by abbana** [comment]
Workaround for those using Swift Package Manager.

1- Download code
2- Copy GoogleSignInSwift files, except GoogleSignInButtonBundleExtensions
3- Remove the imports

Swift version does not use UIScreen

**Comment by mdmathias** [comment]
Closing as a duplication of #353.
