### ISSUE TITLE
Swift package broken for v7.0.0

### ISSUE THREAD

**Issue by trzy** [google/GoogleSignIn-iOS#365]
**Describe the bug**
Added the GoogleSignIn package via the built-in Swift package manager in Xcode 15.2. It appears to be present but cannot "import GoogleSignIn" -- no such module exists. 

**To Reproduce**
Create an Xcode project.
Under "Packages", search and add GoogleSignIn.
Try to "import GoogleSignIn"

**Expected behavior**
I expect the import to succeed and be able to build my project.

**Screenshots**

**Environment**
N/A

**Additional context**

**Comment by yalkhder** [comment]
Couldn't reproduce issue. I was able to successfully add GoogleSignIn to a project.

Reproduction steps:
1. Created new iOS app Xcode project
1. Went to File -> Add Package Dependencies...
1. Entered googlesignin-ios git URL (https://github.com/google/GoogleSignIn-iOS.git) in the search bar in the top right corner
1. Clicked Add Package

**Comment by trzy** [comment]
Did you try to import and build? Because it is clearly not working with new projects here.

**Comment by yalkhder** [comment]
Yes I imported `GoogleSignIn` and called `GIDSignIn.sharedInstance`.

**Comment by trzy** [comment]
So why does this fail consistently on a clean install of Xcode on my Ventura Mac? This is extremely frustrating and as a result, we are considering abandoning Google social sign in altogether for our product. It looks to me like sub-dependencies are failing to import, namely the Firebase one.

**Comment by yalkhder** [comment]
Can you share some more info? Namely:
- Repo/Package.swift file/podspec file
- Stack trace and/or error messages you're seeing
- Any other relevant screenshot, resources, etc...

Thanks

**Comment by trzy** [comment]
Yes, sure, I’ve uploaded the project here, which should have everything needed to see the issue happening: https://github.com/trzy/GoogleSignIn-Test

In GoogleSignInTestApp.swift, you can see the import fail. There is no stack trace, just the singular error message in Xcode.

Thank you,

Bart

**Comment by trzy** [comment]
Thank you! That was exactly it. I would have never noticed it — strangely, my other packages didn’t require me explicitly specifying the target. Might be worth making a note of this and adding a screenshot here: https://developers.google.com/identity/sign-in/ios/start-integrating#swift-package-manager
