### ISSUE TITLE
Calling GIDSignIn.sharedInstance.signIn, no callback is returned after successful authentication

### ISSUE THREAD

**Issue by taro-ken** [google/GoogleSignIn-iOS#377]
**Describe the bug**
Calling GIDSignIn.sharedInstance.signIn, no callback is returned after successful authentication

**To Reproduce**
1. Press the GoogleLogin button and call the `GIDSignIn.sharedInstance.signIn` method
2. Select a valid Google account and proceed
3. permit access

**Expected behavior**
Closure returns a signInResult.

**Screenshots**

https://github.com/google/GoogleSignIn-iOS/assets/67847164/40b18743-d6cc-481b-a1aa-5ddd0067e535

**Environment**
- Device: [ iPhone 14 simulator, M2 MacBook Air ]
- OS: [  iOS 17.0, macOS 13.5 ]

**Additional context**
Pressing the GoogleLogin button to cancel the permission to share information dialog about apps and websites successfully returns an error in Closure.

**Comment by mdmathias** [comment]
I am not sure how the "GoogleLogin" button works. Ultimately, I think it would be that button's job to make sure that the closure is called. The sample apps in this library do not see this issue.

If you're able to reproduce this issue in one of our [sample apps](https://github.com/google/GoogleSignIn-iOS/tree/main/Samples), please comment here with exact reproduction steps and we will investigate.
