### ISSUE TITLE
Add macCatalyst support

### ISSUE THREAD

**Issue by narek-sv** [google/GoogleSignIn-iOS#38]
Hi Google team.

Do you have any raw estimations of when you'll add macCatalyst support?

Thank you

**Comment by petea** [comment]
Hopefully sometime this year.  More detail on future releases coming soon.

**Comment by narek-sv** [comment]
Thanks for the response. Looking forward to it.

**Comment by fnuky** [comment]
I tries catalyst right now and it is working.. :) I made login on catalyst app on big sur

**Comment by fnuky** [comment]
Also working on catalyna and monterey

**Comment by petea** [comment]
Mac Catalyst is now supported with the release of [Google Sign-In 6.1.0](https://github.com/google/GoogleSignIn-iOS/releases/tag/6.1.0).

**Comment by narek-sv** [comment]
Great news, Thanks for the response
