### ISSUE TITLE
App rejected for Mac Catalyst due to opening external browser during Sign-In

### ISSUE THREAD

**Issue by startechm** [google/GoogleSignIn-iOS#388]
**Describe the bug**

My app was rejected and I received the following message from Apple:
<<
The user is taken to the default web browser to sign in or register for an account, which provides a poor user experience.

We advise to update to the latest Google SDK and use “SFSafariViewController” instead of “UIWebView”.

This will ensure that the app correctly implements an account authentication mechanism that does not link users out to Safari.
>>

I am using the latest version as of March 31st 2024.
Even after using the example app inside GoogleSignIn-iOS, this is still opening an external browser. 
This seems to only happen in Mac Catalyst.

**To Reproduce**
1. Get the latest version of GoogleSignIn-iOS repository on a Mac
2. Run "open GoogleSignIn-iOS/Samples/ObjC/SignInSample/SignInSample.xcodeproj" and build/run for Mac catalyst
3. Click on the Sign-In button
4. It opens an external browser and not an in-app browser.

**Expected behavior**
An in-app browser should be opened instead so that Apple doesn't reject apps.

**Screenshots**

**Environment**
- Device: [ MacBook Pro ]
- OS: MacOS 14 (likely earlier versions also)
- Browser: [ your default browser: Safari, Brave, Firefox, ... ]

**Additional context**

**Comment by mdmathias** [comment]
The quote from the app store review above is confusing to me. [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) is used by AppAuth (and thus GoogleSignIn-iOS - what I call 'GSI' below) when running on Mac Catalyst, and is specifically made for authentication via 3rd party services. I'm not aware of any changes in Apple policy on this subject. 

Moreover, neither GSI nor AppAuth use `UIWebView`. Are you perhaps creating your own `UIWebView` somewhere?

Can you confirm the versions of GSI and AppAuth you see in your app? One thing I noticed is that the SignInSample app doesn't declare a Mac Catalyst run destination. Can you verify that you have one for your app? I modified the SignInSample app and you should see something like the below:

<img width="2032" alt="Screenshot 2024-04-01 at 1 56 27 PM" src="https://github.com/google/GoogleSignIn-iOS/assets/4029922/54c49ccf-f928-4ed9-a892-3389f95ba87e">

Another thing: can you set a breakpoint in [`OIDAuthorizationService+IOS.m` at this location](https://github.com/openid/AppAuth-iOS/blob/master/Sources/AppAuth/iOS/OIDAuthorizationService%2BIOS.m#L36)? I want to make sure that the correct user agent is being created for your Mac Catalyst run destination. This is important because `ASWebAuthenticationSession` is used for the auth flow when using Mac Catalyst ([the agent created should eventually call through to here](https://github.com/openid/AppAuth-iOS/blob/master/Sources/AppAuth/iOS/OIDExternalUserAgentCatalyst.m#L81)).

**Comment by ostatnicky** [comment]
+1. The same here. I've been rejected with this reason too.

> Apple: The user is taken to the default web browser to sign in or register for an account, which provides a poor user experience.

**Comment by ostatnicky** [comment]
They report seeing this pop-up window.

![Screenshot 2024-04-02 at 9 10 08AM](https://github.com/google/GoogleSignIn-iOS/assets/597298/e157131b-ec4a-49c1-a808-d599adf8bcf5)

**Comment by ostatnicky** [comment]
> Can you confirm the versions of GSI and AppAuth you see in your app? One thing I noticed is that the SignInSample app doesn't declare a Mac Catalyst run destination. Can you verify that you have one for your app? I modified the SignInSample app and you should see something like the below...

I don't think it's Catalyst related. It's macOS related at all. There is the same popup on the Mac destination in the Sample app.

<img width="549" alt="Screenshot 2024-04-02 at 17 36 04" src="https://github.com/google/GoogleSignIn-iOS/assets/597298/2b2f81d8-9a40-4c25-8a34-6b8a4921be85">

**Comment by mdmathias** [comment]
@ostatnicky are you able to inquire with the reviewer to understand what they want the macOS app to do instead? GSI (via AppAuth) uses `ASWebAuthenticationSession`, which will use the default browser on macOS for the auth flow (see the quote from the documentation below). This is out of our control and is by Apple's design. Additionally, `ASWebAuthenticationSession` is Apple's recommended solution for authentication; so, I'm pretty confused by the rejection per the terms mentioned above. 

"In macOS, the system opens the user’s default browser if it supports web authentication sessions, or Safari otherwise."

https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession

**Comment by ostatnicky** [comment]
@mdmathias Ok, I’ll try to ask them.

**Comment by startechm** [comment]
> The quote from the app store review above is confusing to me. [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) is used by AppAuth (and thus GoogleSignIn-iOS - what I call 'GSI' below) when running on Mac Catalyst, and is specifically made for authentication via 3rd party services. I'm not aware of any changes in Apple policy on this subject.
> 
> Moreover, neither GSI nor AppAuth use `UIWebView`. Are you perhaps creating your own `UIWebView` somewhere?
> 
> Can you confirm the versions of GSI and AppAuth you see in your app? One thing I noticed is that the SignInSample app doesn't declare a Mac Catalyst run destination. Can you verify that you have one for your app? I modified the SignInSample app and you should see something like the below:
> 
> <img alt="Screenshot 2024-04-01 at 1 56 27 PM" width="2000" src="https://private-user-images.githubusercontent.com/4029922/318565831-54c49ccf-f928-4ed9-a892-3389f95ba87e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDg1MDgsIm5iZiI6MTcxMjEwODIwOCwicGF0aCI6Ii80MDI5OTIyLzMxODU2NTgzMS01NGM0OWNjZi1mOTI4LTRlZDktYTg5Mi0zMzg5Zjk1YmE4N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDEzNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM2MTJkZjE1NzYwNTUxZjA1Y2ZiMDNmMDRkYzM1Y2VkYzFkMzU5Nzg2YWY1YzkwNzk4ZjI1OTA1Mzc2ZjRhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ARg8gh8gM2D2yanU0z9fwCKJv1YWciyBLPsaHEr7Luc">
> Another thing: can you set a breakpoint in [`OIDAuthorizationService+IOS.m` at this location](https://github.com/openid/AppAuth-iOS/blob/master/Sources/AppAuth/iOS/OIDAuthorizationService%2BIOS.m#L36)? I want to make sure that the correct user agent is being created for your Mac Catalyst run destination. This is important because `ASWebAuthenticationSession` is used for the auth flow when using Mac Catalyst ([the agent created should eventually call through to here](https://github.com/openid/AppAuth-iOS/blob/master/Sources/AppAuth/iOS/OIDExternalUserAgentCatalyst.m#L81)).



> The quote from the app store review above is confusing to me. [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) is used by AppAuth (and thus GoogleSignIn-iOS - what I call 'GSI' below) when running on Mac Catalyst, and is specifically made for authentication via 3rd party services. I'm not aware of any changes in Apple policy on this subject.
> 
> Moreover, neither GSI nor AppAuth use `UIWebView`. Are you perhaps creating your own `UIWebView` somewhere?
> 
> Can you confirm the versions of GSI and AppAuth you see in your app? One thing I noticed is that the SignInSample app doesn't declare a Mac Catalyst run destination. Can you verify that you have one for your app? I modified the SignInSample app and you should see something like the below:
> 
> <img alt="Screenshot 2024-04-01 at 1 56 27 PM" width="2000" src="https://private-user-images.githubusercontent.com/4029922/318565831-54c49ccf-f928-4ed9-a892-3389f95ba87e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDk0OTgsIm5iZiI6MTcxMjEwOTE5OCwicGF0aCI6Ii80MDI5OTIyLzMxODU2NTgzMS01NGM0OWNjZi1mOTI4LTRlZDktYTg5Mi0zMzg5Zjk1YmE4N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDE1MzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2E0MTViY2M5OTY2YWVjODQ3YzUwYzQzYTM5NzVmMjFlNzc0MzE2N2Y5ODQ1Nzk5NDY1YjBjY2FmNzY4ZTkwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1q_O9waPfnBOa0R0MZ6jBShoVAJLNeYERp75y78TMP0">
> Another thing: can you set a breakpoint in [`OIDAuthorizationService+IOS.m` at this location](https://github.com/openid/AppAuth-iOS/blob/master/Sources/AppAuth/iOS/OIDAuthorizationService%2BIOS.m#L36)? I want to make sure that the correct user agent is being created for your Mac Catalyst run destination. This is important because `ASWebAuthenticationSession` is used for the auth flow when using Mac Catalyst ([the agent created should eventually call through to here](https://github.com/openid/AppAuth-iOS/blob/master/Sources/AppAuth/iOS/OIDExternalUserAgentCatalyst.m#L81)).

@mdmathias I am not creating my own `UIWebView`.  I am just calling `GIDSignIn.sharedInstance.signIn(withPresenting: self) ` from my view controller.  I was able to reproduce with the embedded example.   It appears that Apple may have changed their policy in that regard because in the past, my app was accepted (I never had this issue before).  It appears that they don't want a browser to be opened externally but within the app.

I tried this with GSI version `7.0.0` and `7.1.0`: both builds were rejected.
Regarding the SignInSample app, it does not have Mac Catalyst as a target (I had to configure one).  I also noticed the same behavior if I use the Mac target (designed for iPad) [which was available without adding any new target].

Here is a screenshot of what I have after putting a breakpoint at the location you provided.  Please let me know if there is any particular field you are interested in? (It is painfully slow / I can try to give you more information tomorrow if that works)

<img width="476" alt="image" src="https://github.com/google/GoogleSignIn-iOS/assets/113662993/196d2cc0-7b1e-4a08-9a39-62d961c2b5f3">

One more thing, I saw that another user posted the screenshot that Apple provided showing the reason why the app was rejected: I had the exact same screenshot (with a different app name though).

**Comment by mdmathias** [comment]
@startechm thanks for following up. It does look like you're getting the `ASWebAuthenticationSession` that you're supposed to. If you look above, you will see my comment that this is how `ASWebAuthenticationSession` works on macOS. It will open the default browser and start the auth flow. I'm confused by the rejection because it runs counter to how `ASWebAuthenticationSession` works, and that type is what Apple tells us to use for auth flows. A policy change to use a web flow within a macOS app is essentially the same as saying, "Don't use `ASWebAuthenticationSession`," which hasn't been announced to my knowledge and would be a kind of deprecation of that type. 

I suggest reaching out to the reviewer to ask why your app is getting rejected on macOS for using `ASWebAuthenticationSession`, which is what Apple says to use. 

Link to the class for your convenience:

https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession

**Comment by ostatnicky** [comment]
@mdmathias Yes, I'm waiting for a response from Apple reviewer...

**Comment by ostatnicky** [comment]
@mdmathias Ok, I've got the response from the Apple reviewer:

```
Hello,

Thank you for your reply regarding the external login and Google SDK, and your attempted compliance with the 4.0 guidelines.

We advise to update to the latest Google SDK and use “SFSafariViewController” instead of “UIWebView”.

This will ensure that the app correctly implements an account authentication mechanism that does not link users out to Safari.

We look forward to reviewing your revised binary.

Best regards,

App Review
```

But from what I understand, you're using `SFSafariViewController` there, aren't you?

**Comment by ostatnicky** [comment]
I tried easy example how to present `SFSafariViewController` on macOS and it appears in "poor" way. So, not sure what's is the solution.
```
func openInSafari(url: URL) {
    let config = SFSafariViewController.Configuration()
    config.entersReaderIfAvailable = true

    let vc = SFSafariViewController(url: url, configuration: config)
    present(vc, animated: true)
}
```

**Comment by ostatnicky** [comment]
@mdmathias When I read the documentation it looks that `init(url:callbackURLScheme:completionHandler:)` is going to be deprecated in iOS and Mac Catalyst 17.4. Maybe it's causing the whole issue here. And `AppAuth` is using it in `OIDExternalUserAgentCatalyst.m` on line 82.

https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession 
https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/2990952-init

**Comment by mdmathias** [comment]
Thanks for the reply @ostatnicky. I appreciate it, and I'm sure that this is frustrating for you.

The answer you received seems to repeat the same information. I still don't understand it, as it implies that `ASWebAuthenticationSession` shouldn't be used on macOS, which doesn't make sense to me.

Good find regarding the deprecation of [-[ASWebAuthenticationSession initWithURL:callbackURLScheme:completionHandler:]](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/2990952-init). I will point out that [OIDExternalUserAgentIOS](https://github.com/openid/AppAuth-iOS/blob/eee20d36310e37a26dde368b23c681a7616ec69b/Sources/AppAuth/iOS/OIDExternalUserAgentIOS.m#L108) also uses this method, and it appears that iOS apps are not getting rejected for this reason. This leads me to think the deprecation is not the cause of this rejection, and gives me reason to suspect that the rejection is an error.

I'm not sure what I can do to help on my side, but I will reach out to colleagues and see if they have any ideas. On your side, perhaps you can ask for clarification on whether or not the reviewer is saying that `ASWebAuthenticationSession` shouldn't be used on macOS or Mac Catalyst? 

I will follow up here if I learn anything.

**Comment by ostatnicky** [comment]
@mdmathias I've asked the reviewer about if `ASWebAuthenticationSession` shouldn't be used on macOS or Mac Catalyst and it looks that there are non-technical people. It makes sense. @mdmathias Are you able to connect with Apple to resolve this issue?

```
Hello,

Thank you for your response. 

Regarding Guideline 4.0, should you require more assistance with resolving this issue, [Apple Developer Technical Support](https://developer.apple.com/support/technical/) is available to provide direct one-on-one support for discrete code-level questions.

Best regards,

App Review
```

**Comment by ostatnicky** [comment]
It's funny, I have a screen in my app that use `WKWebView` wrapped to UIViewController and just simply presented and the result looks much better with nice modal screen. But when you try to use `SFSafariViewController` all started to be mess on MacOS :D

**Comment by ostatnicky** [comment]
@startechm Did you resolve it somehow?

**Comment by mdmathias** [comment]
@ostatnicky Unfortunately, I do not personally have the ability to directly connect with anyone at Apple on this. I have talked with colleagues internally and everyone is just as perplexed as we are. I still believe this rejection is a mistake.

That said, perhaps your next step is to schedule a meeting with Apple Developer Technical Support as the reviewer suggests. I imagine that person will look at the situation as we do.

**Comment by startechm** [comment]
> @startechm Did you resolve it somehow?
I have had multiple interactions with Apple but every time they send me about the same answer.  I don't think they are technical also.

I was not able the resolve the issue on my end so I asked for an exemption (because I told them that the previous version worked like this and I will try to fix it in the next version) and they granted it to me but they said that I cannot submit a future version until this is fixed.

It appears that the issue is the fact that it should open a ViewController (so it looks like it is running within the app) instead of opening an external app. For iOS/iPhone it seems to be working as they expect.  Would it be hard to fix the behavior so it opens a ViewController instead of an external app?

If you try to use for example "Firefox" as your default browser, it becomes more obvious that it is opening an external app (browser).

Not sure what can be done at this point.  It is very difficult to contact Apple and get a good answer.

**Comment by ostatnicky** [comment]
@mdmathias @startechm I’ve sent a request for a technical meeting. We will see if they can give us some advice.

**Comment by mattisssa** [comment]
We've received the same rejection reason for the last couple of versions. Our macOS app, not a Catalyst one, doesn't allow control over where the Google SDK redirects users for authentication. 

Any advice on convincing the Apple review team? No success yet.

**Comment by mdmathias** [comment]
Thanks @mattisssa for the note. I will share this will my colleagues internally. 

For you and others on this thread, I'm doing what I can to get clarification and resolution. I will be sure to follow up here when I have something to share.

**Comment by mdmathias** [comment]
Hi @ostatnicky @startechm @mattisssa. We are engaging with Apple to try to better understand this issue. Are you able to share your app name(s)? Please share them here if so. If you're not comfortable sharing on this thread, then please let me know if you'd be able to share if we found a more private mechanism. I can figure something out there.

**Comment by isaacadariku** [comment]
@mdmathias we have the same issue for macOS "Reflection Journal & Prompts".

Here is a screenshot, if they will need the submission ID:
![image](https://github.com/google/GoogleSignIn-iOS/assets/46024202/db3dab4a-fab8-42be-acee-a888b04ba65c)

**Comment by startechm** [comment]
> We are engaging with Apple to try to better understand this issue. Are you able to share your app name(s)? Please share them here if so. If you're not comfortable sharing on this thread, then please let me know if you'd be able to share if we found a more private mechanism. I can figure something out there.

@mdmathias our app name is "logdt - get things done & more".  We have a version on the Mac App Store that has this issue (version `1.7.0` which was initially rejected but we got an exemption assuming we can fix it in the next version).

**Comment by ostatnicky** [comment]
@mdmathias Sure, our app is [Done! – Happy Productivity](https://apps.apple.com/app/done-happy-productivity/id1058049013). The current version in the AppStore already has the "poor experience flow" in the Sign In/Up, so you can try it.

It weird that there is no issue similar like this for the [Facebook iOS SDK](https://github.com/facebook/facebook-ios-sdk/issues). But they have exactly the same flow.

**Comment by ostatnicky** [comment]
@mdmathias Unfortunately, no one has yet replied to my request for the technical support from Apple.

**Comment by mdmathias** [comment]
Thanks @startechm @ostatnicky and @isaacadariku. I will share these names with my colleagues and let you know what I hear.

**Comment by mattisssa** [comment]
@mdmathias  Oops, I missed the discussion.
It's [Spellar AI](https://spellar.ai/)

We passed the review a few times, compelling Apple to approve the submission due to critical bug fixes.

**Comment by ostatnicky** [comment]
@mdmathias Our app (Done!) was approved accidentaly without any further interaction. If this was due to you, thank you very much!

**Comment by tigernghk** [comment]
This issue is critical. All mac catalyst apps are rejected now. 
I know external browser is the behaviour of API.
Are there any workaround or solution?

**Comment by mdmathias** [comment]
@tigernghk I'm doing what I can by raising this issue with colleagues internally who are able to reach out to Apple. Otherwise, @ostatnicky [posted here](https://github.com/google/GoogleSignIn-iOS/issues/388#issuecomment-2056094928) that engaging with Apple Developer Technical Support helped to resolve the rejection.

I will be sure to post here if I receive any update.

**Comment by ghb101** [comment]
My mac catalyst app update was just rejected for this same reason, but I am given the opportunity to have the released approved this time due to bug fixes.  I definitely agree this is critical if Apple is really going to reject any future updates that use Google Sign In calling the default browser.  I do plan to write to the review team to explain that the issue needs to be taken up directly with Apple and Google, and not every developer that uses Google Sign In for a macCatalyst app....we'll see how that goes.

**Comment by mattisssa** [comment]
> I do plan to write to the review team to explain that the issue needs to be taken up directly with Apple and Google, and not every developer that uses Google Sign In for a macCatalyst app....we'll see how that goes.

@ghb101, we've gone through 5-7 releases with the same rejection, and each time, we've tried to explain the issue to Apple. However, this has been utterly futile, as they've insisted that we "fix" the problem. 

Passing the review every time by citing "critical bug fixes" is incredibly frustrating and time-consuming.

**Comment by mdmathias** [comment]
We are doing our best to consult with counterparts at Apple. In the meantime, I think this [message from ostatnicky](https://github.com/google/GoogleSignIn-iOS/issues/388#issuecomment-2056094928) indicates that working with Apple Developer Technical Support (ADTS) will result in an approved submission.

Perhaps if more apps reach out to ADTS, then app store review process will be updated more quickly?

**Comment by tigernghk** [comment]
Google Sign In SDK depends on AppAuth SDK. I have changed code in AppAuth SDK to use WKWebView as embedded browser instead of ASWebAuthenticationSession for quick and dirty way to solve the problem. Specifically, I only have changed the file "OIDExternalUserAgentCatalyst.m". My app is approved eventually.

**Comment by ostatnicky** [comment]
@tigernghk Could you share the "dirty" code with us?

**Comment by tigernghk** [comment]
FYI. Here is my modified code in OIDExternalUserAgentCatalyst.m:

https://github.com/tigernghk/AppAuth_WKWebView/blob/main/OIDExternalUserAgentCatalyst.m

**Comment by mdmathias** [comment]
@tigernghk You shouldn't be using a `WKWebView` for authorization flows. Webviews are disallowed user agents for most identity providers. This is because the developers implementing the webview can inject JavaScript, read cookies, etc. In short, they are not secure for authorization.

**Comment by tigernghk** [comment]
Thanks. I hope you can find better solution.

**Comment by mdmathias** [comment]
@tigernghk Unfortunately, this is not a problem we can solve in GSI or AppAuth. I am of the position that these rejections are an error in app submission review process. The "fix" will come from there. 

In any case, using a web view for authorization will likely lead to a [403 - disallowed_useragent error](https://support.google.com/accounts/answer/12917337?hl=en#403disallowed) when using Sign in with Google. I highly recommend that you change using a web view for sign ins.

**Comment by andytriboletti** [comment]
My Mac game Open Space was also rejected on Testflight. I don't understand why Apple cares. With password managers I prefer external safari anyway. I don't think it makes it any better to handle links in an embedded browser.

**Comment by andytriboletti** [comment]
I sent this to antitrust@ftc.gov - If anyone agrees please email them

https://github.com/google/GoogleSignIn-iOS/issues/388


Apple rejecting mac apps that use Google Sign in external browser sign in. I think its anti trust valid cause they're coming out with their own password manager

**Comment by mattisssa** [comment]
omg, this issue is still open?..

**Comment by mdmathias** [comment]
This should not be occurring any longer. Please let me know if you have an app that was recently rejected for this reason. I will reopen the issue.

**Comment by andytriboletti** [comment]
do we need to update pod files? or resubmit? my mac build was last rejected on Apr 12, 2024 I just sent another version in for approval.
