### ISSUE TITLE
Support for SDK Signature

### ISSUE THREAD

**Issue by sylvia-tencent-wmt** [google/GoogleSignIn-iOS#389]
Apple requires signatures for SDKs starting in spring 2024

Reference:
[Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/ )

I would like to know when you adopt this change.

Describe the solution you'd like
Support SDK signature

**Comment by mdmathias** [comment]
This repo's latest release (7.1.0) provides a privacy manifest. We do not release GSI as a binary. My reading of the documentation at the link you shared means that Google Sign-In iOS is not required to sign the SDK.
