### ISSUE TITLE
Cannot find 'GIDSignInErrorCode' in scope

### ISSUE THREAD

**Issue by JeffersonSchuler** [google/GoogleSignIn-iOS#39]
Since upgrading to v6.0.1 when trying to reference GIDSignInErrorCode in Swift (Xcode 12.5.1) I am now seeing a compiler error of "Cannot find 'GIDSignInErrorCode' in scope".

**Comment by petea** [comment]
In Swift, GIDSignInErrorCode is represented as a struct named GIDSignInError.

**Comment by JeffersonSchuler** [comment]
Thanks, that worked.  Something changed with v6.0 as GIDSignInErrorCode worked in Swift previously.  You can see as in the example here: https://github.com/googlesamples/google-services/blob/master/ios/signin/SignInExampleSwift/AppDelegate.swift

**Comment by petea** [comment]
With the 6.0.0 release we switched to using `NS_ERROR_ENUM` for the definition of `GIDSignInErrorCode`.
