### ISSUE TITLE
Facing compile time error with GoogleSignIn 7.1.0.

### ISSUE THREAD

**Issue by harshil-vyas08** [google/GoogleSignIn-iOS#395]
**Describe the bug**
After updating the pod from 6.0.2 to 7.1.0 I am facing compile time issue.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
![googlesign](https://github.com/google/GoogleSignIn-iOS/assets/157394622/e0a18795-d1ce-4793-8074-3fce3d3359c5)

**Environment**
Xcode Version : 15.3

**Additional context**

**Comment by mdmathias** [comment]
I'm not able to reproduce this issue. It seems like a local issue in your own CocoaPods environment. Perhaps you need to run a `pod repo update`?
