### ISSUE TITLE
Error: Undefined symbol: _idn2_to_unicode_8z8z when try to run on Simulator.

### ISSUE THREAD

**Issue by ChurikiTenna** [google/GoogleSignIn-iOS#41]
On actual device, it works.

But when I try to run on a simulator, 
"Undefined symbol: _idn2_to_unicode_8z8z" and "Undefined symbol: _idn2_to_ascii_8z"
occurs.

**Comment by petea** [comment]
These seem to be errors related to the [Libidn library](https://www.gnu.org/software/libidn/), which Google Sign-In does not depend on.  Could this be coming from elsewhere in your project?

**Comment by ChurikiTenna** [comment]
Oh thanks.
I thought it's coming from GoogleSignIn since this error showed up just after I updated the GoogleSignIn to 6.0.2.

Sorry to bother you.
I'll close this issue:))

Thank you.
