### ISSUE TITLE
Launch GSI 8.0.0

### ISSUE THREAD

**Issue by mdmathias** [google/GoogleSignIn-iOS#418]
1. Publish 8.0.0 tag on GitHub
2. Push podspecs

**Comment by aykutguvendh** [comment]
Hey @mdmathias , I just wanted to know when you are planning to release 8.0.0? The debugger fix introduced [here](https://github.com/google/GoogleSignIn-iOS/pull/403) is something our team is looking forward to. Thank you very much for your support with this issue 🙏

**Comment by mdmathias** [comment]
There are a couple of moving pieces in the background here that have delayed this until the end of July. In the meantime, I think you should be able to update your dependency to the `main` branch.

**Comment by aykutguvendh** [comment]
> There are a couple of moving pieces in the background here that have delayed this until the end of July. In the meantime, I think you should be able to update your dependency to the `main` branch.

Hey @mdmathias , thank you for your responsiveness and all the effort you put in this. Could you please give us an update on the timeline for 8.0.0? Due to our CI checks, we try to use official dependency versions as much as possible although the workaround with the `main` branch is much appreciated.

**Comment by CtrlJone** [comment]
Hello, @mdmathias , when can we update to 8.0.0? We are currently unable to debug normally due to lldb issues.

**Comment by mdmathias** [comment]
The current plan is to release v8.0.0 next week.

**Comment by yarodevuci** [comment]
> The current plan is to release v8.0.0 next week.

Is there any breaking changes from 7.1.0?

**Comment by mdmathias** [comment]
We incremented the minimum version of iOS supported, which led to the major version for the release.

https://github.com/google/GoogleSignIn-iOS/pull/445

**Comment by CtrlJone** [comment]
@mdmathias  hey，Will 8.0.0 be released today?

**Comment by mdmathias** [comment]
https://github.com/google/GoogleSignIn-iOS/releases/tag/8.0.0 released today.
