### ISSUE TITLE
No library for this platform was found MacOS

### ISSUE THREAD

**Issue by DaniilShmoylove** [google/GoogleSignIn-iOS#424]
I am using native **macOS** and have encountered an issue with the absence of a library for my target platform. In this case, I cannot utilize **macOS Catalyst**, so I need to find a way to ensure native support.

<img width="598" alt="Снимок экрана 2024-05-17 в 19 55 48" src="https://github.com/google/GoogleSignIn-iOS/assets/88559460/12a30f61-9784-422c-a6dd-2e4e4312a54c">

Currently, I am attempting to integrate a library using _**xcframework**_, but the project is not compiling for **macOS**. However, everything works fine for **iOS**.

**Error example:** /Users/name/Downloads/AppName/FirebaseBinaries/Frameworks/GoogleSignIn/AppAuth.xcframework:1:1 While building for macOS, no library for this platform was found in '/Users/name/Downloads/AppName/FirebaseBinaries/Frameworks/GoogleSignIn/AppAuth.xcframework'.

<img width="679" alt="Снимок экрана 2024-05-17 в 20 05 38" src="https://github.com/google/GoogleSignIn-iOS/assets/88559460/23dc30f6-cd87-4e6e-8b45-8e49d199db89">

I would appreciate assistance in resolving this problem and finding a way to successfully compile the project for macOS. Any recommendations or tips on this matter would be greatly appreciated.

**Comment by mdmathias** [comment]
We do not distribute GoogleSignIn as a framework. It looks like you're getting GoogleSignIn (and GTMAppAuth and AppAuth) via "FirebaseBinaries"? Is that right? If so, I'd suggest inquiring with the folks producing those frameworks.

**Comment by mdmathias** [comment]
Closing for now since this doesn't appear to be an issue related to this repo. Please let me know if that's incorrect.
