### ISSUE TITLE
GIDSignIn callback never called with EMM error

### ISSUE THREAD

**Issue by pjechris** [google/GoogleSignIn-iOS#43]
Hi,

I noticed that when getting a EMM error from OpenID then my workflow completion block is never called. From my testing:
- I get up to `GIDAuthentication.handleTokenFetchEMMError` with a JSON error:
```json
{
    "error": "emm_passcode_required",
    "error_description": "Access to your account data is restricted by policies within your organization. Please contact the administrator for xxx for more information."
}
```
-  `GIDEMMEErrorHandler.handleErrorFromResponse` is called but `completion` is never called

**Comment by XiangtianDai** [comment]
Will take a look, thanks for raising the issue.

**Comment by XiangtianDai** [comment]
I couldn't reproduce the issue. Which method did you call? For `signInWithConfiguration:presentingViewController:callback:`, in case of EMM error `emm_passcode_required`, the callback method is called after the pop-up dialog to prompt the user for adding passcode is dismissed.

**Comment by pjechris** [comment]
Erf sorry I guess it's on my side then. I indeed use `signInWithConfiguration:presentingViewController:callback:` but never got the pop-up. Probably because I'm using SwiftUI 🤷‍♂️ 

I think we can close the ticket then.
