### ISSUE TITLE
Offline Access Docs

### ISSUE THREAD

**Issue by ajram23** [google/GoogleSignIn-iOS#466]
Is documentation for https://developers.google.com/identity/sign-in/ios/offline-access outdated, the python code seems to be for a deprecated library. Also where can I find the latest way to use obtain serverAuth code. I have tried it a couple of ways and I end up with Access blocked: Authorization Error. Apologies if its the wrong type to post

**Comment by ywsang** [comment]
Hi @ajram23! The backend server-side aspects are not handled by GoogleSignIn-iOS; we're only responsible for the iOS SDK. 

It seems the deprecated `oauth2client` was replaced by [`google-auth`](https://google-auth.readthedocs.io/en/master/), which can be found on GitHub at [google-auth-library-python](https://github.com/googleapis/google-auth-library-python). Maybe someone there can help you find the correct replacement for the methods used from the deprecated library in the code snippet?

**Comment by ajram23** [comment]
@ywsang Hi Yana, Thanks for getting back. Could you kindly let me know how I can request a serverAuth using the SDK? Also is this the same SDK for build MacOSApps as some of your documentation suggests? Please and thank you!

**Comment by ywsang** [comment]
@ajram23 The code snippet for step 2 in the documentation that uses the SDK to retrieve the one-time authorization code is up-to-date. 

And yes, this SDK can be used in macOS environments. There's some setup information in the README [here](https://github.com/google/GoogleSignIn-iOS?tab=readme-ov-file#google-sign-in-on-macos). Sorry if I caused any confusion by mentioning that we're only responsible for the iOS SDK in my earlier comment!

**Comment by ajram23** [comment]
@ywsang No worries. thanks for confirming. I have tried that. I am getting a redirect_uri_mismatch Bad Request error when I try to get credentials with serverAuth code. Is there expectations the redirect URI match? If so what URI should it match? There is not URI in the Client ID for iOS page. Am I missing something? Any help would be greatly appreciated! Please and thank you!

**Comment by ywsang** [comment]
I'm unfamiliar with the credential exchange steps after using the GoogleSignIn-iOS SDK to get the `serverAuthCode`. Again, maybe the [`google-auth-library-python`](https://github.com/googleapis/google-auth-library-python) repo has some issues related to the problem you're experiencing, or someone there would be able to give you guidance.

**Comment by ajram23** [comment]
@ywsang Thanks for your note! FYI, I tried that route before I came here https://github.com/googleapis/google-auth-library-python/issues/1561, dead end and was asked to talk to paid support.

Not on you, but It's pretty disappointing when Google has outdated documentation and one gets ping ponged to get a basic flow going.

**Comment by ywsang** [comment]
Sorry for the frustration -- maybe https://github.com/googleapis/google-auth-library-python/issues/758 is relevant?

**Comment by ajram23** [comment]
@ywsang now I am being told that the server library doesnt support the use case https://github.com/googleapis/google-auth-library-python/issues/1585. At the very least update your docs to say that you wont support it anymore so folks like me dont have to be ping-ponged between teams for weeks. Disappointing!
