### ISSUE TITLE
Alternative to custom URL schemes to prevent OAuth2 impersonation attacks

### ISSUE THREAD

**Issue by samsonjs** [google/GoogleSignIn-iOS#467]
**Is your feature request related to a problem you're having? Please describe.**
As outlined in this post on the Google dev blog, [OAuth2 using custom URL schemes is vulnerable to impersonation attacks](https://developers.googleblog.com/en/improving-user-safety-in-oauth-flows-through-new-oauth-custom-uri-scheme-restrictions/) where malicious apps squat on URL schemes. This is especially a problem for iOS apps because custom URL schemes are currently our only option unless we set up web credentials and implement the auth flow ourselves without this SDK.

**Describe the solution you'd like**
I'd like to set up iOS app credentials in the GCP console that don't use a fixed custom URL scheme for the redirect URI and then use this SDK to authenticate using a domain verified using universal links which are verified.

**Describe alternatives you've considered**
I've considered rolling my own auth flow entirely or using `ASWebAuthenticationSession` with universal links and ditching this SDK. That also requires me to set up a web credential in the GCP console so I can set a custom redirect URI.

**Additional context**
Happy to provide more info on request.

**Comment by brnnmrls** [comment]
Hi! Thanks for raising this security concern and I understand the risks associated with using custom URL schemes for authentication. To provide some more context, we address this issue in two ways: 
1) Proof Key for Code Exchange ([PKCE](https://www.rfc-editor.org/rfc/rfc7636)) 
2) ASWebAuthenticationSession ([ASWAS](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession?changes=latest_minor&language=objc)). 

For PKCE, this option is supported to secure authorization concerns with public clients when custom URI scheme redirects are used. This will ensure that only the app that initiated the authorization request can use the result authorization code. For ASWAS, developers are encouraged to use this for Google Sign-In to handle OAuth redirects using Safari, minimizing the reliance on custom URI schemes. I'd say these are the best options we have at the moment to minimize the risk. Feel free to comment if I'm misunderstanding or if you'd like to provide more context, thanks again!

**Comment by samsonjs** [comment]
Thanks! I'll look into using ASWAS
