### ISSUE TITLE
Invalid error code have been thrown: kGIDSignInErrorCodeUnknown, but should be kGIDSignInErrorCodeCanceled

### ISSUE THREAD

**Issue by Romick2005** [google/GoogleSignIn-iOS#471]
**Describe the bug**
If user cancel google signIn process at latest step (confirming two previous steps), the lib throws error with OIDErrorCodeProgramCanceledAuthorizationFlow that is handled as kGIDSignInErrorCodeUnknown, but it should be the same as OIDErrorCodeUserCanceledAuthorizationFlow has: kGIDSignInErrorCodeCanceled (The user canceled the sign-in flow.)

[Related with react-native-google-signin](https://github.com/react-native-google-signin/google-signin/issues/1327)

**To Reproduce**
1. Go to login with Google
2. Tap on 'Continue' (step 1)
3. Select google account and press 'Continue' (step 2)
4. On the last step select 'Cancel'.
5. See 'Unknown error in google sign in. (kGIDSignInErrorCodeUnknown access_denied)' error, but it should be 'The user canceled the sign-in flow. (kGIDSignInErrorCodeCanceled)'

**Expected behavior**
Expected to see 'The user canceled the sign-in flow' error, not 'Unknown error in google sign in'.

**Screenshots**
![image](https://github.com/user-attachments/assets/896442c2-027d-4f2a-ad06-1836886ca311)

**Environment**
- Device: iPhone XS
- OS: macOS Sonoma 14.5
- Browser: Chrome

**Additional context**
Normal google sign in.

**Comment by brnnmrls** [comment]
Hello, thanks for reporting and issuing a fix! You're right – it seems there's a mismatch between the error codes. We'll get this reviewed and aim to include this fix in our next release.
