### ISSUE TITLE
GoogleSignIn incompatible with Firebase SDK

### ISSUE THREAD

**Issue by rfarrow1010** [google/GoogleSignIn-iOS#477]
**Describe the bug**
I am developing an iOS app with the Firebase SDK and am now trying to implement Sign In with Google. However, when I add this package in SPM, I get the following error message. It seems that this package isn't compatible with the version of app-check that the Firebase SDK depends on. (I can't downgrade the Firebase SDK; they've recently patched a bug I raised for a different issue and shipped it in a new version.)

**To Reproduce**
Add package Firebase 10.26.0

Add GoogleSignIn-ios 8.0.0

```
Failed to resolve dependencies Dependencies could not be resolved because root depends on 'firebase-ios-sdk' 10.26.0..<11.0.0 and root depends on 'googlesignin-ios' 8.0.0..<9.0.0.
'googlesignin-ios' is incompatible with 'firebase-ios-sdk'.
'googlesignin-ios' >= 8.0.0 practically depends on 'app-check' 11.0.0..<12.0.0 because 'googlesignin-ios' 8.0.0 depends on 'app-check' 11.0.0..<12.0.0 and no versions of 'googlesignin-ios' match the requirement 8.0.1..<9.0.0.
'firebase-ios-sdk' 10.26.0..<11.0.0 practically depends on 'app-check' 10.19.0..<11.0.0 because 'firebase-ios-sdk' 10.29.0 depends on 'app-check' 10.19.0..<11.0.0 and 'firebase-ios-sdk' 10.26.0 depends on 'app-check' 10.19.0..<11.0.0.
'firebase-ios-sdk' {10.26.1..<10.29.0, 10.29.1..<11.0.0} practically depends on 'app-check' 10.19.0..<11.0.0 because 'firebase-ios-sdk' 10.28.0 depends on 'app-check' 10.19.0..<11.0.0 and 'firebase-ios-sdk' 10.28.1 depends on 'app-check' 10.19.0..<11.0.0.
'firebase-ios-sdk' {10.26.1..<10.28.0, 10.28.2..<10.29.0, 10.29.1..<11.0.0} practically depends on 'app-check' 10.19.0..<11.0.0 because no versions of 'firebase-ios-sdk' match the requirement {10.26.1..<10.27.0, 10.27.1..<10.28.0, 10.28.2..<10.29.0, 10.29.1..<11.0.0} and 'firebase-ios-sdk' 10.27.0 depends on 'app-check' 10.19.0..<11.0.0.
```

**Expected behavior**
Dependencies should resolve successfully.

**Environment**
- Device: 2019 MacBook Pro (Intel)

**Additional context**
FirebaseAuth works fine, but the docs suggest I need this package to implement Sign In with Google.

**Comment by paulb777** [comment]
Google SignIn 8.x requires Firebase 11.x
Google SignIn 7.x is the limit for Firebase 10.x

**Comment by rfarrow1010** [comment]
I see, downgrading to 7.1.0 seems to work, thanks!
