### ISSUE TITLE
Prompt popup show but cannot see the account list to select.

### ISSUE THREAD

**Issue by jackkudo** [google/GoogleSignIn-iOS#481]
**Describe the bug**
Using iPhone iOS 18.0 click on Google Sign in -> The popup for selecting account appear but cannot see anything or interacting.
![Simulator Screenshot - iPhone 16 - 2024-10-02 at 10 47 36](https://github.com/user-attachments/assets/9397ee67-5e63-41e8-af07-00a47ba19318)

**To Reproduce**
1. Tap on Google Sign In
2. Popup for selecting account appears however cannot interact.

**Expected behavior**
Works as iOS version < 18.0

**Screenshots**
Attached the screenshots

**Environment**
- Device: [iPhone 16]
- OS: [ iOS 18.0 ]

**Comment by Digifais** [comment]
Also seeing this issue here.

**Comment by brnnmrls** [comment]
Hi everyone! I took a look at this and was not able to reproduce the issue. I did a few runs with the repro steps including Xcode 16.0 + iOS 18 but never came across the empty popup screen. 

I'd suggest making sure everything is up to date including the Google Sign-in SDK and simulator's OS, resolve any network issues, and clear the simulator. Furthermore, if it's possible, any stack traces or a full screen recording of the sign-in flow resulting in the blank screen could help us debug. Without being able to repro the error ourselves, we unfortunately can't help much.

**Comment by carlosq-ordering** [comment]
Also seeing this issue here.

**Comment by Digifais** [comment]
Hi @brnnmrls, some more information from my end. On the first run of my app with GoogleSignIn v8.0.0, I'm experiencing the described issue by OP as can be seen in the following screen recording: https://github.com/user-attachments/assets/13e6c47c-ba90-4144-81eb-6a1a2e0fb39e

After this happens, I have to force close my app as the browser viewcontroller isn't responsive. After force closing my app and running it for a second time, the browser refuses to open when pressing my button and I get the following crash report:
[SafariViewService-2024-10-09-231417.txt](https://github.com/user-attachments/files/17318722/SafariViewService-2024-10-09-231417.txt)

After that crash has happened, I can open the browser again as with the first run shown by the screen recording and the same issue occurs as with the first run. Hopefully, this might help you out a bit. There is no real stack trace when the browser does open and gets stuck.

**Comment by mauta-ii-mauta** [comment]
Hello. I am facing a similar issue. Has any one managed to find a fix for it? Or is there an alternative method that can be used outside GoogleSignIn?

**Comment by mauta-ii-mauta** [comment]
> Hi everyone! I took a look at this and was not able to reproduce the issue. I did a few runs with the repro steps including Xcode 16.0 + iOS 18 but never came across the empty popup screen.
> 
> I'd suggest making sure everything is up to date including the Google Sign-in SDK and simulator's OS, resolve any network issues, and clear the simulator. Furthermore, if it's possible, any stack traces or a full screen recording of the sign-in flow resulting in the blank screen could help us debug. Without being able to repro the error ourselves, we unfortunately can't help much.

I really do not know where the issue is coming from, but I assume it may have something to do with GoogleSignIn when presenting the web page Modally so it could be an IOS 18 issue in SFAuthenticationViewController. I notice that when I create a new app with only one button that starts GIDSignIn.sharedInstance.signIn() then works fine. But if the page has multiple text fields, labels, images and other buttons that seems to be when the issue arises. I must note also that I am using Storyboard and not SwiftUI.

**Comment by jackkudo** [comment]
Seem like it doesn't happen on real devices anymore. I closed this issue.

**Comment by hyochan** [comment]
Wait l! It is still happening in iOS simulator 16

**Comment by koenzi132** [comment]
Still happening too. :(

**Comment by dusanristic** [comment]
Hey, quick question, why is this issue closed, as problem is still reproducible on simulators (at least I am still experiencing problem)?

**Comment by hazzo** [comment]
This is happening too while using the `google_sign_in` package on Flutter. Was working perfectly on iOS 17 simulator.

**Comment by simonadenic** [comment]
Hello, are there any updates on the issue? We're still experiencing it on simulators, which prevents us from testing some of the flows in our app (as login with google is disabled).

**Comment by huynamboz** [comment]
Same issue

**Comment by aqigif** [comment]
still exp this issue, is it solved already?
