### ISSUE TITLE
googleSignin authclients not found

### ISSUE THREAD

**Issue by yunsanch** [google/GoogleSignIn-iOS#485]
**Describe the bug**
the Appcheck token is not found, continue to get the following error
Debug> [AppCheckCore][I-GAC003001] Unexpected API response: <NSHTTPURLResponse: 0x600000295080> { URL: https://firebaseappcheck.googleapis.com/v1/oauthClients/(null):exchangeDebugToken } { Status Code: 404, Headers {
} }, body: {
  "error": {
    "code": 404,
    "message": "com.google.apps.framework.request.NotFoundException: Resource not found: oauthClients/(null)",
    "status": "NOT_FOUND"
  }
}
.

**To Reproduce**
1. Go to firebase and set up a project follow the documentations for setting debug appcheck for google identity for ios
2. set the debuglogs in arguments in Xcode, and you will get the error shown above.

**Expected behavior**
that i see verifed request coming from google edentity for ios

**Screenshots**
error says authclients is null, however i have 7 authclients in firebase
![Image](https://github.com/user-attachments/assets/9153e7c3-99a6-47fc-932a-60ee03e91bbc)
![Image](https://github.com/user-attachments/assets/459eef77-382d-4805-93c2-b6e2871515f1)
auth clients are there
![Image](https://github.com/user-attachments/assets/9fd87311-8b0f-4fc7-9aad-956f569b87af)
![Image](https://github.com/user-attachments/assets/d3f4211f-07f9-49cf-8a32-90cd8a731c9d)

**Environment**
- Device: [ e.g. iPhone 13 or  11, simulator ]
- OS: [ e.g. iOS 18 ]

**Additional context**
i have been going over both firebase and google console and everything is set up why do i keep getting an error that there is not auth clients when there are 7. why cant it be found is there something diferent i must do with sing in in order to get that?

**Comment by mdmathias** [comment]
I'm not sure how you have your project set up (in Firebase or in Xcode), but you can take a look at [our App Check sample app](https://github.com/google/GoogleSignIn-iOS/tree/main/Samples/Swift/AppAttestExample) to see how we have things set up. Also, I suggest you go through [the documentation](https://developers.google.com/identity/sign-in/ios/appcheck/get-started) again to see if you missed anything.

One thing I definitely saw in my own work on the sample app linked above was that I would need to make sure that the debug token was correctly saved on my Firebase console project.

**Comment by mdmathias** [comment]
Also, I wonder if the error message `"message": "com.google.apps.framework.request.NotFoundException: Resource not found: oauthClients/(null)",` is a clue...
