### ISSUE TITLE
Sign in request is timing out on request https://oauth2.googleapis.com/token

### ISSUE THREAD

**Issue by jalejos-classpass** [google/GoogleSignIn-iOS#489]
**Describe the bug**
I'm getting a connection error after the user authenticates with Google using `try await GIDSignIn.sharedInstance.signIn(withPresenting:)`, but it then times out on the request to `https://oauth2.googleapis.com/token`. This started popping up suddenly after multiple successful sign in attempts while testing the flow, so I suspect the credentials are setup properly but I might be missing something beyond the method call.  

**To Reproduce**
1. Open login screen
2. Tap on Google Sign In button
3. User successfully authenticates with Google on the auth modal
4. Auth modal dismisses itself
5. After a couple of seconds, the request fails due to time out.

**Expected behavior**
- User successfully Sign In's
- `GIDSignIn.sharedInstance.signIn` either returns an error result, or throws an error if there's a mistake on my end

**Screenshots**
![Image](https://github.com/user-attachments/assets/a886ef3c-5950-4e13-aa3b-d870f55bbaa3)

**Environment**
- Device: iPhone 15 simulator
- OS: iOS 17.5
- Browser: n/a

**Additional context**
I've also been specifically testing moving the project's configuration from CocoaPods to Swift Package Manager, and in doing so was where I started noticing the errors for the first time. I've gone back and reverted my changes but now even the CocoaPods build is failing.

**Comment by jalejos-classpass** [comment]
Looking further into the issue, I looked at the Pod's files and it seems like the authentication does happen properly, but the callback is not being called properly?

![Image](https://github.com/user-attachments/assets/8a0d3bae-11b9-4501-9cbf-744b6ade66e4)

The response has an authorization code, but it lacks all the other properties

![Image](https://github.com/user-attachments/assets/3698ef78-f19b-41fb-b40d-67e409372045)

**Comment by jalejos-classpass** [comment]
Keep in mind that this callback only fails to return an object using `try await GIDSignIn.sharedInstance.signIn(:)` when successfully authenticating. If I were to pre-emptively dismiss the modal, it does successfully invoke the `callback(response, error)` and throws the error successfully

**Comment by mingyokim** [comment]
Hi, unfortunately I was not able to reproduce the issue on my end.

How are you using the method and do you have any code snippets that you can share?

**Comment by jalejos-classpass** [comment]
A couple of additional notes I found that I don't know if they can help:
- As already mentioned, I started inspecting `OIDAuthorizationService.m` and noticed that `(void)didFinishWithResponse:(nullable OIDEndSessionResponse *)response error:(nullable NSError *)error` was being triggered successfully on a successful Google Authentication. However, despite `callback(response, error)` being called properly, it wouldn't trigger the callback that would later on resolve `try await GIDSignIn.sharedInstance.signIn(withPresenting: rootViewController)`. 
  - Another note on this is that closing the modal before completing the Google Authentication would also trigger the `callback(response, error)` line, but in said case the callback would resolve `try await GIDSignIn.sharedInstance.signIn(withPresenting: rootViewController)` as a thrown error. I wonder if it could be related to first responder stuff?
- Since discovering this, I also noticed I didn't properly sign out users using `GIDSignIn.sharedInstance.signOut()`. I doubt it's something where I had to sign out before multiple attempts to login, but I did want to note it just in case

**Comment by mingyokim** [comment]
Hi,

I have tried to reproduce the issue by creating a new project with the following snippet, but was not able to reproduce the behavior - I was able to sign in successfully without any errors: 

```
import SwiftUI
import GoogleSignInSwift
import GoogleSignIn

struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundStyle(.tint)
            Text("Hello, world!")
          GoogleSignInButton {
            Task {
              do {
                let signInResult = try await GIDSignIn.sharedInstance.signIn(withPresenting: UIApplication.shared.windows.first!.rootViewController!)
                print("signInResult: \(signInResult)")
                print("user id token: \(signInResult.user.idToken?.tokenString)")
              } catch {
                print("error: \(error)")
              }
            }
          }
        }
        .padding()
    }
}
```

Result:
```
signInResult: <GIDSignInResult: 0x6000002827e0>
user id token: Optional("eyJhbGciOiJSUzI1NiIsImtpZCI6....etc")
```

I have also tried setting a breakpoint in the same line in OIDAuthorizationService, and I am also getting similar results as you:
![Image](https://github.com/user-attachments/assets/df9aac14-8812-43bc-9f49-98a06b1480e8)

Are you able to try creating a new project with the above snippet and see if you still get the error? I would also suggest verifying that the Info.plist and your OAuth client ID are set up as instructed [here](https://developers.google.com/identity/sign-in/ios/start-integrating).

**Comment by jalejos-classpass** [comment]
@mingyokim Info.plist should be properly set, since making the request without it triggers an error before displaying the Google Auth modal. Additionally this started happening after repeated uses of the Google SSO Sign In, and on my screenshots we can see an authorization code so I know these IDs are set properly.

Before following up on making a separate project, I also made a mock View Controller on our project to display the issue, with the following recordings (excuse the quick editing when authenticating, didn't want to provide my personal email)
The recordings include an example of me using the Sign In function with a completion handler instead of async, but it still portrays the issue we're seeing locally

#### First 30~ seconds of recording
https://github.com/user-attachments/assets/351292f6-8347-43e4-8546-1225e00e4865

#### After 45~ seconds and timeout error
https://github.com/user-attachments/assets/f22d1844-99eb-4de1-91b8-caaf3a88d678


I can try making a new mock project with the same code and Client ID's to see if I can reproduce it again, will reply in a couple of minutes

**Comment by jalejos-classpass** [comment]
@mingyokim I created a new mock project with the same code and Client ID's and this does work properly there, but I'm not sure what the follow up action would be to debugging the issue on my main project. All the config from the Target Info on this new mockup project was copy-pasted from the main project, so I don't see at first glance how this could be a misconfiguration

![Image](https://github.com/user-attachments/assets/c0fa70d9-f098-41d3-86c7-cff88f2548a1)

**Comment by brnnmrls** [comment]
Hey! Glad you're not seeing the issue in the new mock project, especially confirming that the code and Client ID work as expected. It would be good to see what dependency might be sparking the issue. Additionally, it could have something to do with using the Combine framework. Unfortunately we're not too familiar with the framework so I can't help much there, but I'd suggest taking a look at our example app to see how we handle things.

**Comment by jalejos-classpass** [comment]
I found the root cause of the issue. It appears that a dependency we had that was doing network monitoring was clashing with the callbackURL in some way. I've confirmed by disabling that library that the issue was not with GoogleSignIn.
