### ISSUE TITLE
Cannot import GoogleSigIn using SPM

### ISSUE THREAD

**Issue by sandro93** [google/GoogleSignIn-iOS#51]
Importing GoogleSignIn V6.0.1 using Swift Package Manager fails:

<img width="860" alt="Screen Shot 2021-08-17 at 1 15 46 PM" src="https://user-images.githubusercontent.com/5948856/129698824-bc7b93c4-660e-412e-b9ea-efc2bfbda65e.png">

**Comment by petea** [comment]
I'm not able to reproduce this.  Can you tell me what version of Xcode you're using?

**Comment by paulb777** [comment]
Try `Packages` -> `Reset Package Caches`

**Comment by sandro93** [comment]
Reseting caches helped

Thank you.
