### ISSUE TITLE
[Flutter] - macOS Support

### ISSUE THREAD

**Issue by Ahmadre** [google/GoogleSignIn-iOS#59]
Hi there :)

hope you're all doing good.

I implemented Google Sign in for Flutter with the actual plugins repo, but I am getting this:

```sh
[!] The platform of the target `Runner` (macOS 10.15.0) is not compatible with `GoogleSignIn (5.0.2)`, which does not support `macOS`.
```

I assume that this error is related to this repo, but some other issues here saying, that it's working for Big Sur....

any idea someone?

**Edit**:

```sh
[!] The platform of the target `Runner` (macOS 10.15.0) is not compatible with `GoogleSignIn (6.0.2)`, which does not support `macOS`
```

**Comment by petea** [comment]
It looks like Flutter is still building against our previous 5.x binary release and not the recent 6.x source release you see in this repo.  Neither release will build for a macOS target as we don't currently support macOS.
