### ISSUE TITLE
Invalid scheme

### ISSUE THREAD

**Issue by chriscoderdr** [google/GoogleSignIn-iOS#62]
![unnamed](https://user-images.githubusercontent.com/2073238/134710175-218033e8-8128-4915-97bd-7f57c4d93a83.jpg)

So I'm using version 6

`pod 'GoogleSignIn', '~> 6.0'`

it opens the dialog for authentication but says invalid scheme

my code is as following:

```
let signInConfig = GIDConfiguration.init(clientID: "MY_REVERSE_ID");
GIDSignIn.sharedInstance.signIn(with: signInConfig, presenting: visibleViewCtrl) { user, error in
                guard error == nil else { return }
        
                // If sign in succeeded, display the app's main content View.
            }
        }
```

I'm not getting any error in the Xcode console.

**Comment by petea** [comment]
It looks like you may be providing GIDConfiguration with your dot-reversed client ID here when it's expecting the normal client ID value.  The dot-reversed client ID value should only be used when defining the custom URL scheme in your project config.

**Comment by chriscoderdr** [comment]
Indeed, thanks @petea
