### ISSUE TITLE
The simulator is working properly and the real machine is not working properly

### ISSUE THREAD

**Issue by itlijunjie** [google/GoogleSignIn-iOS#73]
The simulator is working properly and the real machine is not working properly

**Comment by itlijunjie** [comment]
The progress bar animation is displayed all the time

**Comment by itlijunjie** [comment]
SFAuthenticationSession start
The ```SFAuthenticationSession``` does not close when the in-app is open

**Comment by petea** [comment]
Could you add screenshots to illustrate?
