### ISSUE TITLE
Enable automatic async/await API generation

### ISSUE THREAD

**Issue by paulb777** [google/GoogleSignIn-iOS#91]
The GSI completion handlers use `callback` as the parameter selector for specifying completion handlers. 

`callback` is not one of the selectors included for automatic async method generation. See https://developer.apple.com/documentation/swift/calling_objective-c_apis_asynchronously

If I manually change the selector in the GIDSignIn.h public header to `completion`, Xcode will auto-generate the API:

![Screen Shot 2022-01-14 at 2 54 16 PM](https://user-images.githubusercontent.com/73870/149595683-b3fd8cbd-4774-4868-8297-73c4e8ffb927.png)

**Comment by peterfriese** [comment]
See [Calling Objective-C APIs Asynchronously | Apple Developer Documentation](http://go/swiftdoc/calling-objective-c-apis-asynchronously) for details. Specifically, if the trailing completion block uses the following names, it will automatically be made available to Swift as an `async` method:

* completion
* withCompletion
* completionHandler
* withCompletionHandler
* completionBlock
* withCompletionBlock
* replyTowithReplyTo
* reply
* replyTo

This is based on [SE 0297](https://github.com/apple/swift-evolution/blob/main/proposals/0297-concurrency-objc.md), which discusses a number of Objective-C [attributes](https://github.com/apple/swift-evolution/blob/main/proposals/0297-concurrency-objc.md#additional-objective-c-attribut) that can be used to guide the translation process.
