### ISSUE TITLE
Running with Mac Catalyst doesn't launch browser to sign in.

### ISSUE THREAD

**Issue by apfritts** [google/GoogleSignIn-iOS#95]
Hi!

I'm trying to get Google sign-in to work with an iOS app + Mac Catalyst, but the Safari browser never launches on macOS in order to actually perform the sign-in. The same project works fine on an iPad simulator.

**Modified Sample Project**
I have modified the sample project to try this out: https://github.com/LovebugLLC/GoogleSignIn-iOS/commit/c5ca41ffc14fdb978d24175cdda88fc524655dd4

**Steps to reproduce my Sample Project edits**
1. Clone GoogleSignIn-iOS project
2. `open Samples/ObjC/SignInSample/SignInSample.xcodeproj`
3. Wait for Xcode to install dependencies
4. Select "SignInSample" target
5. Go to the "General" tab
6. Add Mac Catalyst app
7. Go to the "Signing & Capabilities" tab
8. Select your Development Team
9. Click "+ Capability", and add "Keychain Sharing"
10. Run scheme `SignInSample -> My Mac (Catalyst)`

**Steps to reproduce the issue, after running the app**
1. Tap "Sign in" and you'll see this screen: <img width="791" alt="Screen Shot 2022-01-29 at 16 08 57" src="https://user-images.githubusercontent.com/2000021/151681777-0e478906-1501-468d-bec4-ad9d919232ed.png">
2. Click "Continue"

**Expected results**
Browser launches so I can log in

**Actual results**
No browser shows up

**Other notes**
If I change the run target to an iPad simulator, I am presented with the browser window and login just fine.

**Comment by apfritts** [comment]
2 updates:
1) switching your default browser to Chrome presents the signing window (in Chrome) correctly and lets a user continue
2) I've tested this on the latest macOS 12.3 beta in Safari and it worked once but not twice...

**Comment by idrees1378** [comment]
I am facing this issue on safari when running my iPad app on mac (Designed for iPad). Any update on this one?

**Comment by ghb101** [comment]
I am seeing this issue with my macCatalyst app.
Chrome is set as my default browser.  When I tap on the Google Sign In button on my app at the popup appears saying the App wants to use "google.com" sign in.  Then when I tap continue, the chrome browser current window with tab shows, but no new Sign In window appears.  If I then start Safari (if not opened) or shut down Safari and then start it, then the Google login window shows in a Safari popup login screen.  
I am running Version 99.0.4844.74 (Official Build) (x86_64) of chrome.
I am using macOS 12.3 and Xcode 13.3

This is a real problem as any macOS user that has Chrome set as the default browser will not see a Google Sign in screen unless the start Safari (if not running), or quit and restart Safari.

**Comment by vojtabohm** [comment]
Any updates regarding this issue? In my case I have a plain AppKit macOS app and I am encountering the same exact bug.

**Comment by ghb101** [comment]
It ended up resolving for me by closing Chrome and then reopening Chrome.
Also, perhaps check if there are any Chrome updates.

**Comment by vojtabohm** [comment]
The trouble is that this happens for my end users. They click "Sign in with Google" button, confirm the popup and no browser window is opened (until of course they restart Chrome). This is bad for the user experience and the users are churning because the browser window is not opening. Therefore this bug causes me to lose users... :/

**Comment by ghb101** [comment]
Yeah, I completely understand that.  I have no idea if it has been fixed,
as it's hard to replicate.  I'm guessing not though.  I tend to leave
Chrome open for days or weeks at a time and not restart my computer often.
So users like that are most likely still affected...although I do not know
for sure.
